[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-continue-on-failure"
testpaths = [
    "./tests",
    "./dython"
]
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ELLIPSIS"
