[tool.poetry]
name = "l2r"
version = "0.0.0"
description = "a OpenAI gym environment for high performance autonomous racing"
readme = "README.md"
authors = [
	"Jimmy Herman <jimmyherman29@gmail.com>",
	"Jon Francis <jmf1@cs.cmu.edu>"
]

license = "MIT"
repository = "https://github.com/learn-to-race/l2r"
keywords = [
	"reinforcement learning",
	"racing",
	"robotics",
	"machine learning",
	"computer vision"
]

packages = [
    { include = "l2r", from = "src" }
]

[[tool.poetry.source]]
name = "public"
url = "https://pypi.python.org/simple/"

[tool.poetry.dependencies]
python = "^3.7"
gast = "^0.5"
Pillow = "^7.2.0"
pyzmq = "^19.0"
matplotlib = "^3.4"
numpy = "^1.21"
requests = "^2.18"
ruamel_yaml = "^0.17"
websocket_client = "^1.3"
tqdm = "^4.64"

[tool.poetry.dev-dependencies]
black = "^22.0"
coverage = "^6.0"
flake8 = "^4.0"
pre-commit = "^2.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
