[tool.poetry]
name = "ensembleclustering"
version = "1.0.1"
description = ""
authors = ["Takehiro Sano <tsano430@gmail.com>", "burtonrj <burtonrj@cardiff.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.5"
scipy = "^1.5.0"
pymetis = "2020.1"
scikit-learn = "^1.1.1"
kahypar = "1.1.3"
pytest = "^7.1.2"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
