[tool.poetry]
name = "tok-det-metric"
version = "0.1.6"
description = ""
authors = ["Aneta Melisa Stal <melisa@writer.com>"]

[tool.poetry.dependencies]
python = "^3.8"
datasets = "^2.3.2"
more-itertools = "^8.13.0"
numpy = "^1.23.0"
tqdm = "^4.64.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
