# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigSslCertificateImportedCertificateModify(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'password': 'str',
        'encrypted_password': 'str',
        'project': 'str'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'password': 'password',
        'encrypted_password': 'encrypted_password',
        'project': 'project'
    }

    def __init__(self, name=None, description=None, password=None, encrypted_password=None, project='common'):  # noqa: E501
        """ConfigSslCertificateImportedCertificateModify - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._description = None
        self._password = None
        self._encrypted_password = None
        self._project = None
        self.discriminator = None

        self.name = name
        if description is not None:
            self.description = description
        if password is not None:
            self.password = password
        if encrypted_password is not None:
            self.encrypted_password = encrypted_password
        if project is not None:
            self.project = project

    @property
    def name(self):
        """Gets the name of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501

        可选参数；指定ssl证书的名称, 在配置中必须唯一。  # noqa: E501

        :return: The name of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConfigSslCertificateImportedCertificateModify.

        可选参数；指定ssl证书的名称, 在配置中必须唯一。  # noqa: E501

        :param name: The name of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501

        可选参数；配置描述信息。  # noqa: E501

        :return: The description of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ConfigSslCertificateImportedCertificateModify.

        可选参数；配置描述信息。  # noqa: E501

        :param description: The description of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def password(self):
        """Gets the password of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501

        可选参数；指定私钥加密密码。  # noqa: E501

        :return: The password of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ConfigSslCertificateImportedCertificateModify.

        可选参数；指定私钥加密密码。  # noqa: E501

        :param password: The password of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def encrypted_password(self):
        """Gets the encrypted_password of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501

        可选参数；指定加密的私钥加密密码  # noqa: E501

        :return: The encrypted_password of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :rtype: str
        """
        return self._encrypted_password

    @encrypted_password.setter
    def encrypted_password(self, encrypted_password):
        """Sets the encrypted_password of this ConfigSslCertificateImportedCertificateModify.

        可选参数；指定加密的私钥加密密码  # noqa: E501

        :param encrypted_password: The encrypted_password of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :type: str
        """

        self._encrypted_password = encrypted_password

    @property
    def project(self):
        """Gets the project of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501

        项目名称  # noqa: E501

        :return: The project of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this ConfigSslCertificateImportedCertificateModify.

        项目名称  # noqa: E501

        :param project: The project of this ConfigSslCertificateImportedCertificateModify.  # noqa: E501
        :type: str
        """

        self._project = project

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigSslCertificateImportedCertificateModify, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigSslCertificateImportedCertificateModify):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
