# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigActiveStandbyFaultDetectHealthLevel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'local': 'str',
        'peer': 'str'
    }

    attribute_map = {
        'local': 'local',
        'peer': 'peer'
    }

    def __init__(self, local='LINK-MONITOR', peer='LINK-MONITOR'):  # noqa: E501
        """ConfigActiveStandbyFaultDetectHealthLevel - a model defined in Swagger"""  # noqa: E501

        self._local = None
        self._peer = None
        self.discriminator = None

        if local is not None:
            self.local = local
        if peer is not None:
            self.peer = peer

    @property
    def local(self):
        """Gets the local of this ConfigActiveStandbyFaultDetectHealthLevel.  # noqa: E501

        本端设备的监视器检测级别，link-monitor：关注监视器的检测结果，link-poweron：只关注网口是否上电  # noqa: E501

        :return: The local of this ConfigActiveStandbyFaultDetectHealthLevel.  # noqa: E501
        :rtype: str
        """
        return self._local

    @local.setter
    def local(self, local):
        """Sets the local of this ConfigActiveStandbyFaultDetectHealthLevel.

        本端设备的监视器检测级别，link-monitor：关注监视器的检测结果，link-poweron：只关注网口是否上电  # noqa: E501

        :param local: The local of this ConfigActiveStandbyFaultDetectHealthLevel.  # noqa: E501
        :type: str
        """
        allowed_values = ["LINK-MONITOR", "LINK-POWERON"]  # noqa: E501
        if local not in allowed_values:
            raise ValueError(
                "Invalid value for `local` ({0}), must be one of {1}"  # noqa: E501
                .format(local, allowed_values)
            )

        self._local = local

    @property
    def peer(self):
        """Gets the peer of this ConfigActiveStandbyFaultDetectHealthLevel.  # noqa: E501

        对端设备的监视器检测级别，link-monitor：关注监视器的检测结果，link-poweron：只关注网口是否上电  # noqa: E501

        :return: The peer of this ConfigActiveStandbyFaultDetectHealthLevel.  # noqa: E501
        :rtype: str
        """
        return self._peer

    @peer.setter
    def peer(self, peer):
        """Sets the peer of this ConfigActiveStandbyFaultDetectHealthLevel.

        对端设备的监视器检测级别，link-monitor：关注监视器的检测结果，link-poweron：只关注网口是否上电  # noqa: E501

        :param peer: The peer of this ConfigActiveStandbyFaultDetectHealthLevel.  # noqa: E501
        :type: str
        """
        allowed_values = ["LINK-MONITOR", "LINK-POWERON"]  # noqa: E501
        if peer not in allowed_values:
            raise ValueError(
                "Invalid value for `peer` ({0}), must be one of {1}"  # noqa: E501
                .format(peer, allowed_values)
            )

        self._peer = peer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigActiveStandbyFaultDetectHealthLevel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigActiveStandbyFaultDetectHealthLevel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
