# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigLinkGatewayArpDetect(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'state': 'str',
        'timeout': 'int',
        'interval': 'int'
    }

    attribute_map = {
        'state': 'state',
        'timeout': 'timeout',
        'interval': 'interval'
    }

    def __init__(self, state='DISABLE', timeout=None, interval=None):  # noqa: E501
        """ConfigLinkGatewayArpDetect - a model defined in Swagger"""  # noqa: E501

        self._state = None
        self._timeout = None
        self._interval = None
        self.discriminator = None

        if state is not None:
            self.state = state
        if timeout is not None:
            self.timeout = timeout
        if interval is not None:
            self.interval = interval

    @property
    def state(self):
        """Gets the state of this ConfigLinkGatewayArpDetect.  # noqa: E501

        网关ARP检查启/禁用开关（ENABLE-启用/DISABLE-禁用）  # noqa: E501

        :return: The state of this ConfigLinkGatewayArpDetect.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ConfigLinkGatewayArpDetect.

        网关ARP检查启/禁用开关（ENABLE-启用/DISABLE-禁用）  # noqa: E501

        :param state: The state of this ConfigLinkGatewayArpDetect.  # noqa: E501
        :type: str
        """
        allowed_values = ["ENABLE", "DISABLE"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def timeout(self):
        """Gets the timeout of this ConfigLinkGatewayArpDetect.  # noqa: E501

        超时时间（单位：秒）  # noqa: E501

        :return: The timeout of this ConfigLinkGatewayArpDetect.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this ConfigLinkGatewayArpDetect.

        超时时间（单位：秒）  # noqa: E501

        :param timeout: The timeout of this ConfigLinkGatewayArpDetect.  # noqa: E501
        :type: int
        """

        self._timeout = timeout

    @property
    def interval(self):
        """Gets the interval of this ConfigLinkGatewayArpDetect.  # noqa: E501

        检测时间（单位：秒）  # noqa: E501

        :return: The interval of this ConfigLinkGatewayArpDetect.  # noqa: E501
        :rtype: int
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this ConfigLinkGatewayArpDetect.

        检测时间（单位：秒）  # noqa: E501

        :param interval: The interval of this ConfigLinkGatewayArpDetect.  # noqa: E501
        :type: int
        """

        self._interval = interval

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigLinkGatewayArpDetect, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigLinkGatewayArpDetect):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
