# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigIspAddressGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'addresses': 'list[str]',
        'addresses_ipv6': 'list[str]',
        'whois': 'list[str]',
        'default': 'str'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'addresses': 'addresses',
        'addresses_ipv6': 'addresses_ipv6',
        'whois': 'whois',
        'default': 'default'
    }

    def __init__(self, name=None, description=None, addresses=None, addresses_ipv6=None, whois=None, default='NON-DEFAULT'):  # noqa: E501
        """ConfigIspAddressGroup - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._description = None
        self._addresses = None
        self._addresses_ipv6 = None
        self._whois = None
        self._default = None
        self.discriminator = None

        self.name = name
        if description is not None:
            self.description = description
        if addresses is not None:
            self.addresses = addresses
        if addresses_ipv6 is not None:
            self.addresses_ipv6 = addresses_ipv6
        if whois is not None:
            self.whois = whois
        if default is not None:
            self.default = default

    @property
    def name(self):
        """Gets the name of this ConfigIspAddressGroup.  # noqa: E501

        必选参数；指定isp地址集的名称, 在配置中必须唯一。  # noqa: E501

        :return: The name of this ConfigIspAddressGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConfigIspAddressGroup.

        必选参数；指定isp地址集的名称, 在配置中必须唯一。  # noqa: E501

        :param name: The name of this ConfigIspAddressGroup.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this ConfigIspAddressGroup.  # noqa: E501

        可选参数；配置描述信息。  # noqa: E501

        :return: The description of this ConfigIspAddressGroup.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ConfigIspAddressGroup.

        可选参数；配置描述信息。  # noqa: E501

        :param description: The description of this ConfigIspAddressGroup.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def addresses(self):
        """Gets the addresses of this ConfigIspAddressGroup.  # noqa: E501

        可选参数（和addresses_ipv6不能同时为空）；指定地址集ipv4地址范围。  # noqa: E501

        :return: The addresses of this ConfigIspAddressGroup.  # noqa: E501
        :rtype: list[str]
        """
        return self._addresses

    @addresses.setter
    def addresses(self, addresses):
        """Sets the addresses of this ConfigIspAddressGroup.

        可选参数（和addresses_ipv6不能同时为空）；指定地址集ipv4地址范围。  # noqa: E501

        :param addresses: The addresses of this ConfigIspAddressGroup.  # noqa: E501
        :type: list[str]
        """

        self._addresses = addresses

    @property
    def addresses_ipv6(self):
        """Gets the addresses_ipv6 of this ConfigIspAddressGroup.  # noqa: E501

        可选参数（和addresses不能同时为空）；指定地址集ipv4地址范围。  # noqa: E501

        :return: The addresses_ipv6 of this ConfigIspAddressGroup.  # noqa: E501
        :rtype: list[str]
        """
        return self._addresses_ipv6

    @addresses_ipv6.setter
    def addresses_ipv6(self, addresses_ipv6):
        """Sets the addresses_ipv6 of this ConfigIspAddressGroup.

        可选参数（和addresses不能同时为空）；指定地址集ipv4地址范围。  # noqa: E501

        :param addresses_ipv6: The addresses_ipv6 of this ConfigIspAddressGroup.  # noqa: E501
        :type: list[str]
        """

        self._addresses_ipv6 = addresses_ipv6

    @property
    def whois(self):
        """Gets the whois of this ConfigIspAddressGroup.  # noqa: E501

        可选参数；指定所属服务商信息列表。  # noqa: E501

        :return: The whois of this ConfigIspAddressGroup.  # noqa: E501
        :rtype: list[str]
        """
        return self._whois

    @whois.setter
    def whois(self, whois):
        """Sets the whois of this ConfigIspAddressGroup.

        可选参数；指定所属服务商信息列表。  # noqa: E501

        :param whois: The whois of this ConfigIspAddressGroup.  # noqa: E501
        :type: list[str]
        """

        self._whois = whois

    @property
    def default(self):
        """Gets the default of this ConfigIspAddressGroup.  # noqa: E501

        合法输入为NON-DEFAULT、READONLY和MODIFIABLE  # noqa: E501

        :return: The default of this ConfigIspAddressGroup.  # noqa: E501
        :rtype: str
        """
        return self._default

    @default.setter
    def default(self, default):
        """Sets the default of this ConfigIspAddressGroup.

        合法输入为NON-DEFAULT、READONLY和MODIFIABLE  # noqa: E501

        :param default: The default of this ConfigIspAddressGroup.  # noqa: E501
        :type: str
        """
        allowed_values = ["NON-DEFAULT", "READONLY", "MODIFIABLE"]  # noqa: E501
        if default not in allowed_values:
            raise ValueError(
                "Invalid value for `default` ({0}), must be one of {1}"  # noqa: E501
                .format(default, allowed_values)
            )

        self._default = default

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigIspAddressGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigIspAddressGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
