# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from adapi_sdk.models.config_interface import ConfigInterface  # noqa: F401,E501


class ConfigInterfaceList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'items_length': 'int',
        'items': 'list[ConfigInterface]'
    }

    attribute_map = {
        'items_length': 'items_length',
        'items': 'items'
    }

    def __init__(self, items_length=None, items=None):  # noqa: E501
        """ConfigInterfaceList - a model defined in Swagger"""  # noqa: E501

        self._items_length = None
        self._items = None
        self.discriminator = None

        if items_length is not None:
            self.items_length = items_length
        if items is not None:
            self.items = items

    @property
    def items_length(self):
        """Gets the items_length of this ConfigInterfaceList.  # noqa: E501

        当前页项目数  # noqa: E501

        :return: The items_length of this ConfigInterfaceList.  # noqa: E501
        :rtype: int
        """
        return self._items_length

    @items_length.setter
    def items_length(self, items_length):
        """Sets the items_length of this ConfigInterfaceList.

        当前页项目数  # noqa: E501

        :param items_length: The items_length of this ConfigInterfaceList.  # noqa: E501
        :type: int
        """

        self._items_length = items_length

    @property
    def items(self):
        """Gets the items of this ConfigInterfaceList.  # noqa: E501

        当前项目列表  # noqa: E501

        :return: The items of this ConfigInterfaceList.  # noqa: E501
        :rtype: list[ConfigInterface]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this ConfigInterfaceList.

        当前项目列表  # noqa: E501

        :param items: The items of this ConfigInterfaceList.  # noqa: E501
        :type: list[ConfigInterface]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigInterfaceList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigInterfaceList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
