# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from adapi_sdk.models.config_dns_intranet_record_aaaa_aaaa_records import ConfigDnsIntranetRecordAaaaAaaaRecords  # noqa: F401,E501


class ConfigDnsIntranetRecordAaaa(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'state': 'str',
        'type': 'str',
        'aaaa_records': 'list[ConfigDnsIntranetRecordAaaaAaaaRecords]'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'state': 'state',
        'type': 'type',
        'aaaa_records': 'aaaa_records'
    }

    def __init__(self, name=None, description=None, state='ENABLE', type='AAAA', aaaa_records=None):  # noqa: E501
        """ConfigDnsIntranetRecordAaaa - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._description = None
        self._state = None
        self._type = None
        self._aaaa_records = None
        self.discriminator = None

        self.name = name
        if description is not None:
            self.description = description
        if state is not None:
            self.state = state
        if type is not None:
            self.type = type
        if aaaa_records is not None:
            self.aaaa_records = aaaa_records

    @property
    def name(self):
        """Gets the name of this ConfigDnsIntranetRecordAaaa.  # noqa: E501

        必选参数；内网DNS记录——AAAA记录的域名。  # noqa: E501

        :return: The name of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConfigDnsIntranetRecordAaaa.

        必选参数；内网DNS记录——AAAA记录的域名。  # noqa: E501

        :param name: The name of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this ConfigDnsIntranetRecordAaaa.  # noqa: E501

        可选参数；用来对此配置增加额外的备注。  # noqa: E501

        :return: The description of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ConfigDnsIntranetRecordAaaa.

        可选参数；用来对此配置增加额外的备注。  # noqa: E501

        :param description: The description of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def state(self):
        """Gets the state of this ConfigDnsIntranetRecordAaaa.  # noqa: E501

        可选参数；记录的状态，可选值有：enalbe（启用），disable（禁用）；默认为启用。  # noqa: E501

        :return: The state of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ConfigDnsIntranetRecordAaaa.

        可选参数；记录的状态，可选值有：enalbe（启用），disable（禁用）；默认为启用。  # noqa: E501

        :param state: The state of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :type: str
        """
        allowed_values = ["ENABLE", "DISABLE"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def type(self):
        """Gets the type of this ConfigDnsIntranetRecordAaaa.  # noqa: E501

        可选参数；记录的类型，AAAA记录的类型为aaaa。  # noqa: E501

        :return: The type of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ConfigDnsIntranetRecordAaaa.

        可选参数；记录的类型，AAAA记录的类型为aaaa。  # noqa: E501

        :param type: The type of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :type: str
        """
        allowed_values = ["AAAA"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def aaaa_records(self):
        """Gets the aaaa_records of this ConfigDnsIntranetRecordAaaa.  # noqa: E501

        可选参数；AAAA记录的列表，类型为数组。  # noqa: E501

        :return: The aaaa_records of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :rtype: list[ConfigDnsIntranetRecordAaaaAaaaRecords]
        """
        return self._aaaa_records

    @aaaa_records.setter
    def aaaa_records(self, aaaa_records):
        """Sets the aaaa_records of this ConfigDnsIntranetRecordAaaa.

        可选参数；AAAA记录的列表，类型为数组。  # noqa: E501

        :param aaaa_records: The aaaa_records of this ConfigDnsIntranetRecordAaaa.  # noqa: E501
        :type: list[ConfigDnsIntranetRecordAaaaAaaaRecords]
        """

        self._aaaa_records = aaaa_records

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigDnsIntranetRecordAaaa, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigDnsIntranetRecordAaaa):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
