# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ConfigServiceMonitorFtp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'type': 'str',
        'timeout': 'int',
        'interval': 'int',
        'host': 'str',
        'port': 'int',
        'debug_mode': 'str',
        'username': 'str',
        'password': 'str',
        'pk_password': 'str',
        'encrypted_password': 'str',
        'access_path': 'str',
        'ftp_mode': 'str'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'type': 'type',
        'timeout': 'timeout',
        'interval': 'interval',
        'host': 'host',
        'port': 'port',
        'debug_mode': 'debug_mode',
        'username': 'username',
        'password': 'password',
        'pk_password': 'pk_password',
        'encrypted_password': 'encrypted_password',
        'access_path': 'access_path',
        'ftp_mode': 'ftp_mode'
    }

    def __init__(self, name=None, description=None, type='FTP', timeout=None, interval=None, host='*', port=None, debug_mode='DISABLE', username='anonymous', password=None, pk_password=None, encrypted_password=None, access_path='/', ftp_mode='PASV'):  # noqa: E501
        """ConfigServiceMonitorFtp - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._description = None
        self._type = None
        self._timeout = None
        self._interval = None
        self._host = None
        self._port = None
        self._debug_mode = None
        self._username = None
        self._password = None
        self._pk_password = None
        self._encrypted_password = None
        self._access_path = None
        self._ftp_mode = None
        self.discriminator = None

        self.name = name
        if description is not None:
            self.description = description
        if type is not None:
            self.type = type
        if timeout is not None:
            self.timeout = timeout
        if interval is not None:
            self.interval = interval
        if host is not None:
            self.host = host
        if port is not None:
            self.port = port
        if debug_mode is not None:
            self.debug_mode = debug_mode
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if pk_password is not None:
            self.pk_password = pk_password
        if encrypted_password is not None:
            self.encrypted_password = encrypted_password
        if access_path is not None:
            self.access_path = access_path
        if ftp_mode is not None:
            self.ftp_mode = ftp_mode

    @property
    def name(self):
        """Gets the name of this ConfigServiceMonitorFtp.  # noqa: E501

        必选参数；指定监视器的名称, 在配置中必须唯一。  # noqa: E501

        :return: The name of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConfigServiceMonitorFtp.

        必选参数；指定监视器的名称, 在配置中必须唯一。  # noqa: E501

        :param name: The name of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；用来对此配置增加额外的备注。  # noqa: E501

        :return: The description of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ConfigServiceMonitorFtp.

        可选参数；用来对此配置增加额外的备注。  # noqa: E501

        :param description: The description of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def type(self):
        """Gets the type of this ConfigServiceMonitorFtp.  # noqa: E501

        只读参数；监视器类型。  # noqa: E501

        :return: The type of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ConfigServiceMonitorFtp.

        只读参数；监视器类型。  # noqa: E501

        :param type: The type of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """
        allowed_values = ["FTP"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def timeout(self):
        """Gets the timeout of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；设置监视超时时间。  # noqa: E501

        :return: The timeout of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this ConfigServiceMonitorFtp.

        可选参数；设置监视超时时间。  # noqa: E501

        :param timeout: The timeout of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: int
        """
        if timeout is not None and timeout > 86400:  # noqa: E501
            raise ValueError("Invalid value for `timeout`, must be a value less than or equal to `86400`")  # noqa: E501
        if timeout is not None and timeout < 1:  # noqa: E501
            raise ValueError("Invalid value for `timeout`, must be a value greater than or equal to `1`")  # noqa: E501

        self._timeout = timeout

    @property
    def interval(self):
        """Gets the interval of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；设置监视间隔时间。  # noqa: E501

        :return: The interval of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: int
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this ConfigServiceMonitorFtp.

        可选参数；设置监视间隔时间。  # noqa: E501

        :param interval: The interval of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: int
        """
        if interval is not None and interval > 86400:  # noqa: E501
            raise ValueError("Invalid value for `interval`, must be a value less than or equal to `86400`")  # noqa: E501
        if interval is not None and interval < 1:  # noqa: E501
            raise ValueError("Invalid value for `interval`, must be a value greater than or equal to `1`")  # noqa: E501

        self._interval = interval

    @property
    def host(self):
        """Gets the host of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；支持ip地址和*;默认为*，表示监视节点池中的地址；当启用gateway_detect时必须指定ip地址  # noqa: E501

        :return: The host of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this ConfigServiceMonitorFtp.

        可选参数；支持ip地址和*;默认为*，表示监视节点池中的地址；当启用gateway_detect时必须指定ip地址  # noqa: E501

        :param host: The host of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """

        self._host = host

    @property
    def port(self):
        """Gets the port of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；指定监视端口；取值范围[0,65535]，默认为21  # noqa: E501

        :return: The port of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this ConfigServiceMonitorFtp.

        可选参数；指定监视端口；取值范围[0,65535]，默认为21  # noqa: E501

        :param port: The port of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: int
        """
        if port is not None and port > 65535:  # noqa: E501
            raise ValueError("Invalid value for `port`, must be a value less than or equal to `65535`")  # noqa: E501
        if port is not None and port < 0:  # noqa: E501
            raise ValueError("Invalid value for `port`, must be a value greater than or equal to `0`")  # noqa: E501

        self._port = port

    @property
    def debug_mode(self):
        """Gets the debug_mode of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；调试模式开关，disable表示禁用，enable表示启用；默认禁用。  # noqa: E501

        :return: The debug_mode of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._debug_mode

    @debug_mode.setter
    def debug_mode(self, debug_mode):
        """Sets the debug_mode of this ConfigServiceMonitorFtp.

        可选参数；调试模式开关，disable表示禁用，enable表示启用；默认禁用。  # noqa: E501

        :param debug_mode: The debug_mode of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """
        allowed_values = ["ENABLE", "DISABLE"]  # noqa: E501
        if debug_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `debug_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(debug_mode, allowed_values)
            )

        self._debug_mode = debug_mode

    @property
    def username(self):
        """Gets the username of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；指定FTP的用户名，默认为anonymous  # noqa: E501

        :return: The username of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ConfigServiceMonitorFtp.

        可选参数；指定FTP的用户名，默认为anonymous  # noqa: E501

        :param username: The username of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """
        if username is not None and len(username) > 63:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `63`")  # noqa: E501
        if username is not None and len(username) < 1:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `1`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；指定FTP用户的密码  # noqa: E501

        :return: The password of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ConfigServiceMonitorFtp.

        可选参数；指定FTP用户的密码  # noqa: E501

        :param password: The password of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """
        if password is not None and len(password) > 63:
            raise ValueError("Invalid value for `password`, length must be less than or equal to `63`")  # noqa: E501
        if password is not None and len(password) < 0:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `0`")  # noqa: E501

        self._password = password

    @property
    def pk_password(self):
        """Gets the pk_password of this ConfigServiceMonitorFtp.  # noqa: E501

        旧密码  # noqa: E501

        :return: The pk_password of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._pk_password

    @pk_password.setter
    def pk_password(self, pk_password):
        """Sets the pk_password of this ConfigServiceMonitorFtp.

        旧密码  # noqa: E501

        :param pk_password: The pk_password of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """

        self._pk_password = pk_password

    @property
    def encrypted_password(self):
        """Gets the encrypted_password of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；经过加密处理的FTP用户密码  # noqa: E501

        :return: The encrypted_password of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._encrypted_password

    @encrypted_password.setter
    def encrypted_password(self, encrypted_password):
        """Sets the encrypted_password of this ConfigServiceMonitorFtp.

        可选参数；经过加密处理的FTP用户密码  # noqa: E501

        :param encrypted_password: The encrypted_password of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """

        self._encrypted_password = encrypted_password

    @property
    def access_path(self):
        """Gets the access_path of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；指定监控FTP服务的目录,默认为/  # noqa: E501

        :return: The access_path of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._access_path

    @access_path.setter
    def access_path(self, access_path):
        """Sets the access_path of this ConfigServiceMonitorFtp.

        可选参数；指定监控FTP服务的目录,默认为/  # noqa: E501

        :param access_path: The access_path of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """
        if access_path is not None and len(access_path) > 1024:
            raise ValueError("Invalid value for `access_path`, length must be less than or equal to `1024`")  # noqa: E501
        if access_path is not None and len(access_path) < 1:
            raise ValueError("Invalid value for `access_path`, length must be greater than or equal to `1`")  # noqa: E501

        self._access_path = access_path

    @property
    def ftp_mode(self):
        """Gets the ftp_mode of this ConfigServiceMonitorFtp.  # noqa: E501

        可选参数；指定访问FTP的模式,默认为pasv,表示被动模式  # noqa: E501

        :return: The ftp_mode of this ConfigServiceMonitorFtp.  # noqa: E501
        :rtype: str
        """
        return self._ftp_mode

    @ftp_mode.setter
    def ftp_mode(self, ftp_mode):
        """Sets the ftp_mode of this ConfigServiceMonitorFtp.

        可选参数；指定访问FTP的模式,默认为pasv,表示被动模式  # noqa: E501

        :param ftp_mode: The ftp_mode of this ConfigServiceMonitorFtp.  # noqa: E501
        :type: str
        """
        allowed_values = ["PASV", "PORT"]  # noqa: E501
        if ftp_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `ftp_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(ftp_mode, allowed_values)
            )

        self._ftp_mode = ftp_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigServiceMonitorFtp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigServiceMonitorFtp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
