# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from adapi_sdk.models.stat_dns_proxy_dns_servers import StatDnsProxyDnsServers  # noqa: F401,E501


class StatDnsProxy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dns_servers': 'list[StatDnsProxyDnsServers]'
    }

    attribute_map = {
        'dns_servers': 'dns_servers'
    }

    def __init__(self, dns_servers=None):  # noqa: E501
        """StatDnsProxy - a model defined in Swagger"""  # noqa: E501

        self._dns_servers = None
        self.discriminator = None

        if dns_servers is not None:
            self.dns_servers = dns_servers

    @property
    def dns_servers(self):
        """Gets the dns_servers of this StatDnsProxy.  # noqa: E501

        dns服务器列表  # noqa: E501

        :return: The dns_servers of this StatDnsProxy.  # noqa: E501
        :rtype: list[StatDnsProxyDnsServers]
        """
        return self._dns_servers

    @dns_servers.setter
    def dns_servers(self, dns_servers):
        """Sets the dns_servers of this StatDnsProxy.

        dns服务器列表  # noqa: E501

        :param dns_servers: The dns_servers of this StatDnsProxy.  # noqa: E501
        :type: list[StatDnsProxyDnsServers]
        """

        self._dns_servers = dns_servers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatDnsProxy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatDnsProxy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
