# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from adapi_sdk.models.stat_statistic_instant import StatStatisticInstant  # noqa: F401,E501


class StatLinkWanApplicationThroughputApplication1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'general_throughput': 'StatStatisticInstant'
    }

    attribute_map = {
        'type': 'type',
        'general_throughput': 'general_throughput'
    }

    def __init__(self, type=None, general_throughput=None):  # noqa: E501
        """StatLinkWanApplicationThroughputApplication1 - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._general_throughput = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if general_throughput is not None:
            self.general_throughput = general_throughput

    @property
    def type(self):
        """Gets the type of this StatLinkWanApplicationThroughputApplication1.  # noqa: E501

        应用类型  # noqa: E501

        :return: The type of this StatLinkWanApplicationThroughputApplication1.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this StatLinkWanApplicationThroughputApplication1.

        应用类型  # noqa: E501

        :param type: The type of this StatLinkWanApplicationThroughputApplication1.  # noqa: E501
        :type: str
        """
        allowed_values = ["GAME", "VIDEO", "BANK", "OTHER"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def general_throughput(self):
        """Gets the general_throughput of this StatLinkWanApplicationThroughputApplication1.  # noqa: E501

        应用流量  # noqa: E501

        :return: The general_throughput of this StatLinkWanApplicationThroughputApplication1.  # noqa: E501
        :rtype: StatStatisticInstant
        """
        return self._general_throughput

    @general_throughput.setter
    def general_throughput(self, general_throughput):
        """Sets the general_throughput of this StatLinkWanApplicationThroughputApplication1.

        应用流量  # noqa: E501

        :param general_throughput: The general_throughput of this StatLinkWanApplicationThroughputApplication1.  # noqa: E501
        :type: StatStatisticInstant
        """

        self._general_throughput = general_throughput

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatLinkWanApplicationThroughputApplication1, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatLinkWanApplicationThroughputApplication1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
