# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StatActiveStandbyDeviceStatusTraffic(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'health': 'str',
        'failure_reason': 'str'
    }

    attribute_map = {
        'health': 'health',
        'failure_reason': 'failure_reason'
    }

    def __init__(self, health=None, failure_reason=None):  # noqa: E501
        """StatActiveStandbyDeviceStatusTraffic - a model defined in Swagger"""  # noqa: E501

        self._health = None
        self._failure_reason = None
        self.discriminator = None

        if health is not None:
            self.health = health
        if failure_reason is not None:
            self.failure_reason = failure_reason

    @property
    def health(self):
        """Gets the health of this StatActiveStandbyDeviceStatusTraffic.  # noqa: E501

        业务健康状态  # noqa: E501

        :return: The health of this StatActiveStandbyDeviceStatusTraffic.  # noqa: E501
        :rtype: str
        """
        return self._health

    @health.setter
    def health(self, health):
        """Sets the health of this StatActiveStandbyDeviceStatusTraffic.

        业务健康状态  # noqa: E501

        :param health: The health of this StatActiveStandbyDeviceStatusTraffic.  # noqa: E501
        :type: str
        """
        allowed_values = ["NORMAL", "LINK-OFFLINE", "LINK-FAILURE", "UNKNOWN"]  # noqa: E501
        if health not in allowed_values:
            raise ValueError(
                "Invalid value for `health` ({0}), must be one of {1}"  # noqa: E501
                .format(health, allowed_values)
            )

        self._health = health

    @property
    def failure_reason(self):
        """Gets the failure_reason of this StatActiveStandbyDeviceStatusTraffic.  # noqa: E501

        故障原因详情  # noqa: E501

        :return: The failure_reason of this StatActiveStandbyDeviceStatusTraffic.  # noqa: E501
        :rtype: str
        """
        return self._failure_reason

    @failure_reason.setter
    def failure_reason(self, failure_reason):
        """Sets the failure_reason of this StatActiveStandbyDeviceStatusTraffic.

        故障原因详情  # noqa: E501

        :param failure_reason: The failure_reason of this StatActiveStandbyDeviceStatusTraffic.  # noqa: E501
        :type: str
        """

        self._failure_reason = failure_reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatActiveStandbyDeviceStatusTraffic, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatActiveStandbyDeviceStatusTraffic):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
