# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from adapi_sdk.models.stat_pool_summary_node_count_health import StatPoolSummaryNodeCountHealth  # noqa: F401,E501
from adapi_sdk.models.stat_pool_summary_node_count_state import StatPoolSummaryNodeCountState  # noqa: F401,E501


class StatPoolSummaryNodeCount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'int',
        'state': 'StatPoolSummaryNodeCountState',
        'health': 'StatPoolSummaryNodeCountHealth'
    }

    attribute_map = {
        'total': 'total',
        'state': 'state',
        'health': 'health'
    }

    def __init__(self, total=None, state=None, health=None):  # noqa: E501
        """StatPoolSummaryNodeCount - a model defined in Swagger"""  # noqa: E501

        self._total = None
        self._state = None
        self._health = None
        self.discriminator = None

        if total is not None:
            self.total = total
        if state is not None:
            self.state = state
        if health is not None:
            self.health = health

    @property
    def total(self):
        """Gets the total of this StatPoolSummaryNodeCount.  # noqa: E501

        节点个数  # noqa: E501

        :return: The total of this StatPoolSummaryNodeCount.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this StatPoolSummaryNodeCount.

        节点个数  # noqa: E501

        :param total: The total of this StatPoolSummaryNodeCount.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def state(self):
        """Gets the state of this StatPoolSummaryNodeCount.  # noqa: E501


        :return: The state of this StatPoolSummaryNodeCount.  # noqa: E501
        :rtype: StatPoolSummaryNodeCountState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this StatPoolSummaryNodeCount.


        :param state: The state of this StatPoolSummaryNodeCount.  # noqa: E501
        :type: StatPoolSummaryNodeCountState
        """

        self._state = state

    @property
    def health(self):
        """Gets the health of this StatPoolSummaryNodeCount.  # noqa: E501


        :return: The health of this StatPoolSummaryNodeCount.  # noqa: E501
        :rtype: StatPoolSummaryNodeCountHealth
        """
        return self._health

    @health.setter
    def health(self, health):
        """Sets the health of this StatPoolSummaryNodeCount.


        :param health: The health of this StatPoolSummaryNodeCount.  # noqa: E501
        :type: StatPoolSummaryNodeCountHealth
        """

        self._health = health

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatPoolSummaryNodeCount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatPoolSummaryNodeCount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
