# Generated by uml2django - 
# https://steelkiwi.com/blog/best-practices-working-django-models-python/
# https://learndjango.com/tutorials/django-best-practices-models
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

class Subject(
    models.Model
):
    title = models.CharField(
        max_length=255,
        unique=True,
        verbose_name=_('title'),
        help_text=_('title help text'),
    )
    name = models.CharField(
        max_length=255,
        unique=True,
        verbose_name=_('name'),
        help_text=_('name help text'),
    )

    slug = models.SlugField(null=False, unique=True) 

    class Meta:
        verbose_name = _("subject")
        verbose_name_plural = _("subjects")

    # def __str__(self): 
    #     return self.

    def get_absolute_url(self):
        return reverse("subject-detail", args=[str(self.id)])
