from PyEasy.PyEasy import ranNum
from PyEasy.PyEasy import ranFloat
from PyEasy.PyEasy import append
from PyEasy.PyEasy import write
from PyEasy.PyEasy import osName
from PyEasy.PyEasy import cap
from PyEasy.PyEasy import package
from PyEasy.PyEasy import runCmd
from PyEasy.PyEasy import py2dmg
from PyEasy.PyEasy import py2exe
from PyEasy.PyEasy import read
from PyEasy.PyEasy import create
