language: python
python:
  - 3.8
os:
  - linux
  - osx
install:
  # ----- Install and set up Miniconda -----
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create the conda environment
  - conda env create -f environment-dev.yml
  - source activate graphein-dev
  - pip install pytest

  # ----- Install Graphein -----
  - python setup.py install
script:
  # Your test script goes here
  - pytest -vvv tests/
after_success:
  - conda install codecov
  - codecov
