[build-system]
requires = ["build>=0.8.0", "setuptools>=62.0.0", "wheel>=0.37.1"]
build-backend = "setuptools.build_meta"

[project]
name = "ctimed_rotating_file_handler"
version = "0.1.0"
description = "TimedRotatingFileHandler using ctime instead of mtime to determine rollover times."
readme = "README.md"
authors = [
    { name = "silmaril", email = "python@silmaril.de" },
]
license = { file = "LICENSE" }
dependencies = [
    "win32-setctime==1.1.0; platform_system == 'Windows'",
]
requires-python = ">=3.9"
classifiers = [
#    "Development Status :: 3 - Alpha",
#    "Development Status :: 4 - Beta",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]

[project.urls]
"Homepage" = "https://codeberg.org/silmaril/CTimedRotatingFileHandler"
"Bug Tracker" = "https://codeberg.org/silmaril/CTimedRotatingFileHandler/issues"