[tool.poetry]
name = "testfull_pack"
version = "0.1.2"
description = ""
authors = ["Denis Kustov"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.1.1"
logsmal = "^0.0.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
