DanhSach24TietKhi = ["Lập xuân",
                     "Vũ Thủy",
                     "Kinh trập",
                     "Xuân phân",
                     "Thanh minh",
                     "Cốc vũ",
                     "Lập hạ",
                     "Tiểu mãn",
                     "Mang chủng",
                     "Hạ chí",
                     "Tiểu thử",
                     "Đại thử",
                     "Lập thu",
                     "Xử thử",
                     "Bạch lộ",
                     "Thu phân",
                     "Hàn lộ",
                     "Sương giáng",
                     "Lập đông",
                     "Tiểu tuyết",
                     "Đại tuyết",
                     "Đông chí",
                     "Tiểu hàn",
                     "Đại hàn"]
Can = ["GIÁP",
       "ẤT",
       "BÍNH",
       "ĐINH",
       "MẬU",
       "KỶ",
       "CANH",
       "TÂN",
       "NHÂM",
       "QUÝ"]
Chi = ["TÝ",
       "SỬU",
       "DẦN",
       "MÃO",
       "THÌN",
       "TỊ",
       "NGỌ",
       "MÙI",
       "THÂN",
       "DẬU",
       "TUẤT",
       "HỢI"]
DanhSach60CanChi = ["GIÁP TÝ",
                    "ẤT SỬU",
                    "BÍNH DẦN",
                    "ĐINH MÃO",
                    "MẬU THÌN",
                    "KỶ TỊ",
                    "CANH NGỌ",
                    "TÂN MÙI",
                    "NHÂM THÂN",
                    "QUÝ DẬU",
                    "GIÁP TUẤT",
                    "ẤT HỢI",
                    "BÍNH TÝ",
                    "ĐINH SỬU",
                    "MẬU DẦN",
                    "KỶ MÃO",
                    "CANH THÌN",
                    "TÂN TỊ",
                    "NHÂM NGỌ",
                    "QUÝ MÙI",
                    "GIÁP THÂN",
                    "ẤT DẬU",
                    "BÍNH TUẤT",
                    "ĐINH HỢI",
                    "MẬU TÝ",
                    "KỶ SỬU",
                    "CANH DẦN",
                    "TÂN MÃO",
                    "NHÂM THÌN",
                    "QUÝ TỊ",
                    "GIÁP NGỌ",
                    "ẤT MÙI",
                    "BÍNH THÂN",
                    "ĐINH DẬU",
                    "MẬU TUẤT",
                    "KỶ HỢI",
                    "CANH TÝ",
                    "TÂN SỬU",
                    "NHÂM DẦN",
                    "QUÝ MÃO",
                    "GIÁP THÌN",
                    "ẤT TỊ",
                    "BÍNH NGỌ",
                    "ĐINH MÙI",
                    "MẬU THÂN",
                    "KỶ DẬU",
                    "CANH TUẤT",
                    "TÂN HỢI",
                    "NHÂM TÝ",
                    "QUÝ SỬU",
                    "GIÁP DẦN",
                    "ẤT MÃO",
                    "BÍNH THÌN",
                    "ĐINH TỊ",
                    "MẬU NGỌ",
                    "KỶ MÙI",
                    "CANH THÂN",
                    "TÂN DẬU",
                    "NHÂM TUẤT",
                    "QUÝ HỢI"]
NguHanhNapAmTuongUngCanChi = ["KIM",
                              "KIM",
                              "HỎA",
                              "HỎA",
                              "MỘC",
                              "MỘC",
                              "THỔ",
                              "THỔ",
                              "KIM",
                              "KIM",
                              "HỎA",
                              "HỎA",
                              "THỦY",
                              "THỦY",
                              "THỔ",
                              "THỔ",
                              "KIM",
                              "KIM",
                              "MỘC",
                              "MỘC",
                              "THỦY",
                              "THỦY",
                              "THỔ",
                              "THỔ",
                              "HỎA",
                              "HỎA",
                              "MỘC",
                              "MỘC",
                              "THỦY",
                              "THỦY",
                              "KIM",
                              "KIM",
                              "HỎA",
                              "HỎA",
                              "MỘC",
                              "MỘC",
                              "THỔ",
                              "THỔ",
                              "KIM",
                              "KIM",
                              "HỎA",
                              "HỎA",
                              "THỦY",
                              "THỦY",
                              "THỔ",
                              "THỔ",
                              "KIM",
                              "KIM",
                              "MỘC",
                              "MỘC",
                              "THỦY",
                              "THỦY",
                              "THỔ",
                              "THỔ",
                              "HỎA",
                              "HỎA",
                              "MỘC",
                              "MỘC",
                              "THỦY",
                              "THỦY"]
