[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["moviemaker"]

[tool.black]
line-length = 119
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.isort]
line_length = 119
multi_line_output = 3
include_trailing_comma = true

[project]
name = "moviemaker"
version = "0.0.1"
authors = [
  { name="Antonio Bulgheroni", email="antonio.bulgheroni@gmail.com" },
]

description = "An ultra simple image to movie converter."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'PyQt5 >= 5.9.2',
  'tifffile >= 2022.5.4',
  'Pillow >= 9.1.1',
  'moviepy >= 1.0.3',
]

[project.urls]
"Homepage" = "https://github.com/abulgher/moviemaker"
