[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.mypy]
show_column_numbers = true
show_error_codes = true

warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true

disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true

disable_error_code = "no-any-return"

[tool.pylint.basic]
good-names = [
  "i",
  "ex",
  "T",
]

[tool.pylint.design]
max-attributes=100
max-public-methods=100
max-locals=50

[tool.pylint.format]
max-line-length = 79

[tool.pylint.messages-control]
disable = [
  "attribute-defined-outside-init",
  "invalid-name",
  "logging-fstring-interpolation",
  "missing-function-docstring",
  "missing-module-docstring",
  "no-self-use",
  "protected-access",
  "too-few-public-methods",
]

[tool.setuptools_scm]
