__author__ = "Jia Jia"
__author_email__ = "angersax@sina.com"
__description__ = "Lint Work"
__license__ = "Apache-2.0"
__title__ = "lintwork"
__url__ = "https://github.com/devops-lintflow/lintwork"
__version__ = "1.11.0"
