# Form implementation generated from reading ui file '/home/detlev/Development/Python/Eric/eric7-22.7.1/eric/eric7/PipInterface/PipLicensesDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PipLicensesDialog(object):
    def setupUi(self, PipLicensesDialog):
        PipLicensesDialog.setObjectName("PipLicensesDialog")
        PipLicensesDialog.resize(600, 750)
        PipLicensesDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(PipLicensesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.environmentLabel = QtWidgets.QLabel(PipLicensesDialog)
        self.environmentLabel.setObjectName("environmentLabel")
        self.verticalLayout.addWidget(self.environmentLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(PipLicensesDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.licenseFilterComboBox = QtWidgets.QComboBox(PipLicensesDialog)
        self.licenseFilterComboBox.setObjectName("licenseFilterComboBox")
        self.horizontalLayout.addWidget(self.licenseFilterComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.localCheckBox = QtWidgets.QCheckBox(PipLicensesDialog)
        self.localCheckBox.setChecked(True)
        self.localCheckBox.setObjectName("localCheckBox")
        self.horizontalLayout_4.addWidget(self.localCheckBox)
        self.userCheckBox = QtWidgets.QCheckBox(PipLicensesDialog)
        self.userCheckBox.setObjectName("userCheckBox")
        self.horizontalLayout_4.addWidget(self.userCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.licensesList = QtWidgets.QTreeWidget(PipLicensesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.licensesList.sizePolicy().hasHeightForWidth())
        self.licensesList.setSizePolicy(sizePolicy)
        self.licensesList.setAlternatingRowColors(True)
        self.licensesList.setRootIsDecorated(False)
        self.licensesList.setItemsExpandable(False)
        self.licensesList.setWordWrap(True)
        self.licensesList.setObjectName("licensesList")
        self.verticalLayout.addWidget(self.licensesList)
        self.summaryList = QtWidgets.QTreeWidget(PipLicensesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.summaryList.sizePolicy().hasHeightForWidth())
        self.summaryList.setSizePolicy(sizePolicy)
        self.summaryList.setAlternatingRowColors(True)
        self.summaryList.setRootIsDecorated(False)
        self.summaryList.setItemsExpandable(False)
        self.summaryList.setWordWrap(True)
        self.summaryList.setObjectName("summaryList")
        self.verticalLayout.addWidget(self.summaryList)
        self.buttonBox = QtWidgets.QDialogButtonBox(PipLicensesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PipLicensesDialog)
        self.buttonBox.accepted.connect(PipLicensesDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(PipLicensesDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PipLicensesDialog)
        PipLicensesDialog.setTabOrder(self.licenseFilterComboBox, self.localCheckBox)
        PipLicensesDialog.setTabOrder(self.localCheckBox, self.userCheckBox)
        PipLicensesDialog.setTabOrder(self.userCheckBox, self.licensesList)
        PipLicensesDialog.setTabOrder(self.licensesList, self.summaryList)

    def retranslateUi(self, PipLicensesDialog):
        _translate = QtCore.QCoreApplication.translate
        PipLicensesDialog.setWindowTitle(_translate("PipLicensesDialog", "Package Licenses"))
        self.label.setText(_translate("PipLicensesDialog", "License Filter:"))
        self.licenseFilterComboBox.setToolTip(_translate("PipLicensesDialog", "Select the license to filter the packages list"))
        self.localCheckBox.setToolTip(_translate("PipLicensesDialog", "Select to show only licenses of locally installed packages"))
        self.localCheckBox.setText(_translate("PipLicensesDialog", "Local packages only"))
        self.userCheckBox.setToolTip(_translate("PipLicensesDialog", "Select to show only licenses of packages installed to the user-site"))
        self.userCheckBox.setText(_translate("PipLicensesDialog", "User-Site only"))
        self.licensesList.setSortingEnabled(True)
        self.licensesList.headerItem().setText(0, _translate("PipLicensesDialog", "Package"))
        self.licensesList.headerItem().setText(1, _translate("PipLicensesDialog", "Version"))
        self.licensesList.headerItem().setText(2, _translate("PipLicensesDialog", "License"))
        self.summaryList.setSortingEnabled(True)
        self.summaryList.headerItem().setText(0, _translate("PipLicensesDialog", "Count"))
        self.summaryList.headerItem().setText(1, _translate("PipLicensesDialog", "License"))
