[tool.poetry]
name = "drfexts"
version = "0.12.0"
readme = "README.md"
description = "Django Restframework Utils"
authors = ["aiden <allaher@icloud.com>"]
keywords = ["django", "restframework"]
homepage = "https://github.com/aiden520/drfexts"
repository = "https://github.com/aiden520/drfexts"
license = "Apache-2.0"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.8"
django = "^3.2"
django-storages = ">=1.12.3"
django-filter = ">=21.1"
djangorestframework = ">=3.12.4"
pip = ">=21.3.1"
djangorestframework-csv = "^2.1.1"
openpyxl = ">=3.0.9"
pydantic = "=1.8.2"
orjson = "^3.6.7"
django-currentuser = "^0.5.3"
char = "^0.1.2"
conditions = "^0.2.0"

[tool.poetry.dev-dependencies]
#pytest = "^4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
