[tool.poetry]
name = "jaypeg"
version = "0.1.2"
description = "A command line tool for converting and resizing image files."
authors = ["apjanco <apjanco@upenn.edu>"]
readme = "README.md"

[tool.poetry.scripts]
rick-portal-gun = "jaypeg.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.4.1"}
Pillow = "^9.1.1"
filetype = "^1.0.13"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
