from .building import BuildingCreateView
from .building import BuildingDeleteView
from .building import BuildingDetailView
from .building import BuildingListView
from .building import BuildingUpdateView
from .classroom import ClassRoomCreateView
from .classroom import ClassRoomDeleteView
from .classroom import ClassRoomDetailView
from .classroom import ClassRoomListView
from .classroom import ClassRoomUpdateView
from .workingperiod import WorkingPeriodCreateView
from .workingperiod import WorkingPeriodDeleteView
from .workingperiod import WorkingPeriodDetailView
from .workingperiod import WorkingPeriodListView
from .workingperiod import WorkingPeriodUpdateView
