[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PyPeermap"
version = "0.0.1.1"
authors = [
  { name="Naseem Alsadi", email="nalsadi01@gmail.com" },
]
description = "pypeermap is a simple python tool for obtaining all the IP addresses on your local network. "
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
