[tool.coverage.paths]
source = [
    "src",
    "*/site-packages",
]

[tool.coverage.run]
branch = true
source = [
    "aiocronjob",
]

[tool.coverage.report]
fail_under = 100
precision = 2
exclude_lines = [
    "pragma: not covered",
    "@overload",
    "raise AssertionError",
    "raise NotImplementedError",
    "pass",
    "except ImportError:",
]

[tool.black]
line-length = 88
target-version = [
    "py38",
]
include = "\\.pyi?$"
exclude = "\n(\n  /(\n      \\.eggs         # exclude a few common directories in the\n    | \\.git          # root of the project\n    | \\.hg\n    | \\.mypy_cache\n    | \\.tox\n    | \\.venv\n    | _build\n    | buck-out\n    | dist\n  )/\n  | foo.py           # also separately exclude a file named foo.py in\n                     # the root of the project\n)\n"

[tool.pdm]
includes = [
    "README.md",
    "src/aiocronjob/build/**/*",
]

[tool.pdm.dev-dependencies]
dev = [
    "coverage[toml]>=5.1",
    "codecov>=2.1.11",
    "black>=20.8b1",
    "httpx>=0.17.1",
]

[build-system]
requires = [
    "pdm-pep517",
]
build-backend = "pdm.pep517.api"

[project]
name = "aiocronjob"
version = "0.4.0"
description = "Schedule async tasks and manage them using a REST API or WEB UI"
authors = [
    { name = "devtud", email = "devtud@gmail.com" },
]
dependencies = [
    "fastapi>=0.55.1",
    "uvicorn>=0.11.5",
    "crontab>=0.22.8",
    "pytz>=2020.1",
    "aiofiles>=0.5.0",
]
requires-python = ">=3.8, <3.11"
readme = "README.md"
maintainers = [
    { name = "devtud", email = "devtud@gmail.com" },
]
keywords = [
    "async tasks",
    "crontab",
    "rest api",
]

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/devtud/aiocronjob"
repository = "https://github.com/devtud/aiocronjob"
