
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-30T15:27:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b01044c1cac0b3432e329918288dbb97dd7194a",
 "version": "0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
