[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "torutils"
version = "0.0.1"
authors = [
  { name="Rommel Rodriguez Perez", email="alrodperez@gmail.com" },
]
description = "Tor Proxying Library to spin multiple Tor connections"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/rommel-rodriguez/torutils/"
"Bug Tracker" = "https://github.com/rommel-rodriguez/torutils/issues"
