title = "ribbity-docs"
site_name = "ribbity docs"
site_url = "https://ctb.github.io/ribbity-docs/"
github_repo = "ctb/ribbity-docs"

add_pages = [ "index.md", "examples.md", "labels.md" ]

github_username = 'ctb'

issues_dump = 'ribbity-docs.dmp'
