[project]
name = "hkg_ws_utils"
version = "1.0.2"
authors = [
  { name="appropriatefair", email="kajsldf@proton.me" },
]
description = "A small ws package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"