[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "binaryconv"
version = "0.0.1"
authors = [
  { name="Buggem" },
]
description = "Binary converter for Python"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[project.urls]
"GitHub" = "https://github.com/Buggem/binaryconv"
"Bugs and Glitches" = "https://github.com/Buggem/binaryconv/issues"
