# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
        exclude: .svg$
    -   id: end-of-file-fixer
        exclude: .svg$

# -   repo: https://github.com/pycqa/flake8
#     rev: 3.8.4  # pick a git hash / tag to point to
#     hooks:
#     -   id: flake8
