[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "hcjflex"
version = "0.0.1"
authors = [
  { name="acteam", email="acteam1245@gmail.com" },
]
description = "hcjflex, native html/css/javascript gui library for python"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/acteam-ux/hcjflex"
"Bug Tracker" = "https://github.com/acteam-ux/hcjflex/issues"
