[tool.poetry]
name = "dj-stripe"
version = "2.7.0-beta.1"
description = "Django + Stripe made easy"
license = "MIT"
authors = [
    "Alexander Kavanaugh <alex@kavdev.io>",
    "Jerome Leclanche <jerome@leclan.ch>",
]
readme = "docs/README.md"
repository = "https://github.com/dj-stripe/dj-stripe"
documentation = "https://dj-stripe.github.io/dj-stripe/"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Topic :: Office/Business :: Financial",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
]

packages = [
    { include = "djstripe" }
]
include = [
    "AUTHORS.md",
    "CONTRIBUTING.md",
    "HISTORY.md",
    "LICENSE",
]
exclude = [
    "manage.py"
]

[tool.poetry.dependencies]
python = "^3.7.12"
django = ">=3.2, <4.1"
jsonfield = ">=3.0"
stripe = ">=2.48.0"
mkdocs = {version = "^1.3.0", optional = true}
mkdocstrings = {version = "^0.16.0", optional = true}
mkdocs-material = {version = "^8.2.15", optional = true}
mkdocs-autorefs = {version = "^0.3.0", optional = true}
mike = {version = "^1.1.2", optional = true}
jinja2 = {version = "<3.1.0", optional = true}

[tool.poetry.dev-dependencies]
black = "^22.3.0"
psycopg2 = "^2.8.5"
mysqlclient = ">=1.4.0"
flake8 = "^3.9.2"
isort = "^5.10.1"
pre-commit = "^2.19.0"
pytest = "^7.1.2"
pytest-django = "^4.5.2"
mypy = "^0.950"

[tool.poetry.extras]
docs = ["mkdocs", "mkdocstrings", "mkdocs-material", "mkdocs-autorefs", "psycopg2", "mike", "jinja2"]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
