[build-system]
requires = ["setuptools>=62.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hsto-rename"
version = "0.1.0"
authors = [
  { name="aadiyatul"},
]
description = "A script for formatting image tags and replacing image links in Markdown and HTML"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]

dependencies = [
    "pillow >= 9.2.0",
    "requests >= 2.28.0",
]

[project.urls]
"Homepage" = "https://github.com/aadiyatul/hsto-rename"