[project]
name = "Rh-s-PyTool"
version = "0.1.6"
description = "Python code instruments that could be used for index comprehensive evaluation."
authors = [
    { name = "skahanium", email = "skahanium@gmail.com" },
]
readme = "README.md"
dependencies = [
    "numpy>=1.22.3",
    "plum-dispatch>=1.6",
]
requires-python = ">=3.10, <3.11"

[project.license]
text = "MIT"

[project.urls]
Github = "https://github.com/skahanium/Rh-s-PyTool"
Documentation = "https://skahanium.github.io/Rh-s-PyTool/"

[project.optional-dependencies]
others = [
    "pandas",
    "openpyxl",
    "pyecharts",
    "notebook",
]

[tool.pdm]
allow_prereleases = true

[tool.pdm.dev-dependencies]
lint = [
    "autopep8",
]
test = [
    "pytest",
    "pytest-cov",
]
doc = [
    "mkdocs-material",
    "mkdocs",
]

[tool.pdm.build]
package-dir = "src"

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
