from .addons_installer import AddonsInstaller
from .addons_installer import AddonsRegistry
from .addons_installer import AddonsFinder
from .api import LocalAddonsResult
from .api import KeySuffix
from .api import AddonsSuffix
from .git_addons import GitOdooAddons
from .git_addons import GitOdooAddonsResult
from .git_addons import GitSubDirOdooAddons
from .local_addons import LocalOdooAddons
from .local_addons import LocalSubDirOdooAddons
