[tool.poetry]
name = "katz"
version = "0.1.0"
description = ""
authors = ["Kevin Katz <kevcmk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
paho-mqtt = "^1.6.1"
python-osc = "^1.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
