from .SchoolarPeriodCreateView import SchoolarPeriodCreateView
from .SchoolarPeriodDeleteView import SchoolarPeriodDeleteView
from .SchoolarPeriodDetailView import SchoolarPeriodDetailView
from .SchoolarPeriodListView import SchoolarPeriodListView
from .SchoolarPeriodUpdateView import SchoolarPeriodUpdateView
