"""Модуль настройки уровня логирования"""

LOGGING_LEVELS = {
    0: 'RUBBISH',
    20: 'DEBUG',
    40: 'INFO',
    60: 'WARNING',
    80: 'ERROR',
    100: 'CRITICAL',
}

DEBUG_DEFAULT_LOGGING_LEVEL = 1
INFO_DEFAULT_LOGGING_LEVEL = 21
WARNING_DEFAULT_LOGGING_LEVEL = 41
ERROR_DEFAULT_LOGGING_LEVEL = 61
CRITICAL_DEFAULT_LOGGING_LEVEL = 81
