[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "nimgame"
description = "The Game of Nim"
authors = [
    {name = "Karoly Jozsa", email = "karolyjozsa@gmail.com"}
]
readme = "README.txt"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.5"
dynamic = ["version"]
keywords = [
    "nim",
    "game",
    "heap",
    "straw",
    "stack",
    "match",
]

[project.urls]
Home = "http://bitbucket.org/netcreator/nimgame"
Documentation = "https://nimgame.readthedocs.io/en/latest/"
TryIt = "http://donno.yet.com"

[project.scripts]
nimgame = "nimgame:main"
