[tool.poetry]
name = "pyupdater-cos-plugin"
version = "0.1.1"
description = ""
authors = ["杨志勇 <eye.zhi@gmail.com>"]
packages = [
    {include = "uploader"},
]


[tool.poetry.dependencies]
python = "^3.7"
cos-python-sdk-v5 = "^1.9.20"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
