[tool.poetry]
name = "mxfold2"
version = "0.1.1"
description = "RNA secondary structure prediction using deep neural networks with thermodynamic integrations"
authors = ["Kengo Sato <satoken@bio.keio.ac.jp>"]
repository = "https://github.com/keio-bioinformatics/mxfold2"
readme = "README.md"
license = "MIT"
build = "build.py"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18"
torch = "^1.4"
torchvision = "^0"
tqdm = "^4.40"
wheel = "^0.35.1"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"
jupyter = "^1.0.0"
pandas = "^1.1.0"
tensorboard = "^2.3.0"
setuptools_cpp = "^0.1.0"

[tool.poetry.scripts]
mxfold2 = "mxfold2.__main__:main"

[build-system]
requires = ["poetry>=0.12", "setuptools", "wheel", "setuptools-cpp"]
build-backend = "poetry.masonry.api"