[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyzab"
version = "0.0.4"
authors = [
  { name="Lucas Rocha Abraão", email="lucasrabraao@gmail.com" },
]
description = "Simple Python implementation of the Zabbix API."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "python-dotenv",
]

packages = [
  { include = "src" }
]

[project.urls]
"Homepage" = "https://github.com/LucasRochaAbraao/pyzab"
"Bug Tracker" = "https://github.com/LucasRochaAbraao/pyzab/issues"