[tool.poetry]
name = "max-char-match"
version = "1.3.0"
description = "MaxCharMatch metric"
authors = ["melisa-writer <melisa@writer.com>"]

[tool.poetry.dependencies]
python = "^3.8"
diff-match-patch = "^20200713"
more-itertools = "^8.12.0"
numpy = "^1.22.3"
tqdm = "^4.64.0"
datasets = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
