[build-system]
requires = ["setuptools>=61.0", "python-dotenv==0.20.0", "requests==2.27.1"]
build-backend = "setuptools.build_meta"

[project]
name = "simple_pushover"
version = "0.0.5"
authors = [
  { name="Christopher Hedrick", email="cmhedrick@protonmail.com" },
]
description = "A simple and easy to use package to help send push notifications via pushover.net."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://gitlab.com/cmhedrick/pushover/-/tree/main"
"Bug Tracker" = "https://gitlab.com/cmhedrick/pushover/-/issues"