[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "smartmethod"
version = "0.0.3"
authors = [
	{ name="j0ey1iu" }
]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://gitee.com/j0ey1iu/smart-method"
