site_name: Django Ninja
site_description: Django Ninja - Django REST framework with high performance, easy to learn, fast to code.
site_url: https://django-ninja.rest-framework.com
repo_name: vitalik/django-ninja
repo_url: https://github.com/vitalik/django-ninja
edit_uri: ""
google_analytics:
  - UA-170474207-1
  - auto
theme:
  name: material
  palette:
    primary: green
  logo: img/docs-logo.png
  favicon: img/favicon.png
  language: en
  icon:
    repo: fontawesome/brands/github-alt
nav:
  - Intro: index.md
  - motivation.md
  - Tutorial / Reference:
      - tutorial/index.md
      - tutorial/path-params.md
      - tutorial/query-params.md
      - tutorial/body.md
      - tutorial/form-params.md
      - tutorial/file-params.md
      - tutorial/response-schema.md
      - tutorial/crud.md
      - tutorial/django-pydantic.md
      - Advanced Schema:
          - tutorial/django-pydantic-create-schema.md
          - tutorial/config-pydantic.md
      - tutorial/authentication.md
      - tutorial/routers.md
      - tutorial/urls.md
      - tutorial/pagination.md
      - tutorial/operation_params.md
      - tutorial/versioning.md
      - tutorial/request-parsers.md
      - tutorial/response-renderers.md
      - tutorial/errors.md
      - tutorial/csrf.md
      - tutorial/management-commands.md
      - tutorial/api-docs.md
  - async-support.md
  - video.md
  - Enhancement Proposals:
      - Intro: proposals/index.md
      - proposals/cbv.md
      - proposals/v1.md
  - help.md
  - releases.md
markdown_extensions:
  - markdown_include.include
  - markdown.extensions.codehilite:
      guess_lang: false
  # Uncomment these 2 lines during development to more easily add highlights
  #- pymdownx.highlight:
  #    linenums: true
  - codehilite
  - admonition
  - pymdownx.superfences
