[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.check-manifest]
ignore = [".editorconfig", ".pre-commit-config.yaml", "Pipfile", "Pipfile.lock"]

[tool.black]
line-length = 120
target-version = ["py37"]

[tool.mypy]
python_version = "3.7"
mypy_path = "src"

# show error messages from unrelated files
follow_imports = "normal"

# suppress errors about unsatisfied imports
ignore_missing_imports = true

# be strict
warn_return_any = false
warn_no_return = true
warn_redundant_casts = true
warn_unused_ignores = true

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
asyncio_mode = "strict"
addopts = "--cov --cov-append"
