[tool.poetry]
name = "mytwitch"
version = "0.11.3"
description = "Twitch API interaction"
readme = "README.md"
authors = ["Maximillian Strand <maximillian.strand@protonmail.com>"]
repository = "https://gitlab.com/OpenDisrupt/mytwitch"
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.10"
lzon = "^0.1.0"
websockets = "^10.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
