[tool.poetry]
name = "laproxy"
version = "1.0.0"
description = "An easy proxy to setup"
authors = ["Riccardo Isola <riky.isola@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
requests = "^2.28.0"
pytest-timeout = "^2.1.0"
aiohttp = "^3.8.1"
tox = "^3.25.1"
tox-pyenv = "^1.1.0"
tox-poetry = "^0.4.1"
tox-gh-actions = "^2.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
timeout = 5

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38,py310
isolated_build=true

[gh-actions]
python =
    3.8: python3
    3.10: python3

[testenv]
commands = pytest
"""