[tool.poetry]
name = "proyecto2"
version = "0.1.0"
description = ""
authors = ["Isaac Bustos <jibustos@utpl.edu.ec>"]

keywords = ["Temperatura", "Sensado"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
saludo = 'proyecto2.main:main'
