[tool.black]
line-length = 130
target_version = ["py310"]
include = '''
(
    ^/tests/.*[.]py$
  | ^/mb_std/.*[.]py$
  | ^/setup[.]py
)
'''
exclude = '''
(
     __pycache__
     | .venv
)
'''

[tool.isort]
line_length = 130
use_parentheses = "True"
include_trailing_comma = "True"
multi_line_output = 3
default_section = "THIRDPARTY"
known_first_party = "mb_std"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.mypy]
python_version = "3.10"
warn_no_return = false

[tool.pytest.ini_options]
addopts = "-n auto"
markers = ["proxy: requires access proxies", "telegram: requires a telegram bot"]
