[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "xplainable"
version = "0.0.0"
authors = [
  { name="xplainable pty ltd", email="tim@xplainable.io" },
]
description = "Explainable Machine Learning API"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
