[tool.poetry]
name = "ra-utils"
version = "1.2.0"
description = "Utilities for OS2mo/LoRa"
authors = ["Magenta <info@magenta.dk>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://magenta.dk/"
repository = "https://git.magenta.dk/rammearkitektur/ra-utils"
keywords = ["os2mo", "lora"]

[tool.poetry.dependencies]
python = "^3.8"
more-itertools = "^8.13.0"
Jinja2 = { version = "^3.0.1", optional = true }
pydantic = { version = "^1.8.2", optional = true }
requests = { version = "^2.26.0", optional = true }
types-requests = { version = "^2.25.0", optional = true }
sentry-sdk = {version = "^1.5.12", optional = true}
frozendict = "2.1.0"
structlog = "^21.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.6.0"
flake8 = "^4.0.1"
mypy = "^0.961"
reorder-python-imports = "^3.1.0"
pre-commit = "^2.19.0"
parameterized = "^0.8.1"
hypothesis = "^6.48.2"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.1"
mkdocs-material = "^8.3.8"
mkdocstrings = "^0.19.0"
pytest-asyncio = "^0.18.3"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.poetry.extras]
jinja = ["Jinja2"]
pydantic = ["pydantic"]
frozendict = ["frozendict"]
sentry = ["sentry-sdk", "pydantic"]
headers = ["pydantic", "requests", "types-requests"]
all = ["Jinja2", "pydantic", "requests", "types-requests", "frozendict", "sentry-sdk"]

[tool.autopub]
git-username = "MagentaBot"
git-email = "info@magenta.dk"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
