from .SubjectLevelCreateView import SubjectLevelCreateView
from .SubjectLevelDeleteView import SubjectLevelDeleteView
from .SubjectLevelDetailView import SubjectLevelDetailView
from .SubjectLevelListView import SubjectLevelListView
from .SubjectLevelUpdateView import SubjectLevelUpdateView
