[project]
name = "micropip"
version = "0.0.1"
authors = [
  { name="Michael Droettboom", email="mdroettboom@mozilla.com" },
]
description = "A small version of pip for running in pyodide"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pyodide/pyodide"
"Bug Tracker" = "https://github.com/pyodide/pyodide/issues"
