from .student import StudentCreateView
from .student import StudentDeleteView
from .student import StudentDetailView
from .student import StudentListView
from .student import StudentUpdateView
from .instructor import InstructorCreateView
from .instructor import InstructorDeleteView
from .instructor import InstructorDetailView
from .instructor import InstructorListView
from .instructor import InstructorUpdateView
