# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from layerapi.api.service.account import account_api_pb2 as api_dot_service_dot_account_dot_account__api__pb2


class AccountAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccountViewByName = channel.unary_unary(
                '/api.AccountAPI/GetAccountViewByName',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameResponse.FromString,
                )
        self.GetAccountViewById = channel.unary_unary(
                '/api.AccountAPI/GetAccountViewById',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdResponse.FromString,
                )
        self.GetMyAccountView = channel.unary_unary(
                '/api.AccountAPI/GetMyAccountView',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewResponse.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/api.AccountAPI/CreateAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateAccountResponse.FromString,
                )
        self.CreateOrganizationAccount = channel.unary_unary(
                '/api.AccountAPI/CreateOrganizationAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountResponse.FromString,
                )
        self.CreateApiKey = channel.unary_unary(
                '/api.AccountAPI/CreateApiKey',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyResponse.FromString,
                )
        self.ToggleDatasetLikeByMyAccount = channel.unary_unary(
                '/api.AccountAPI/ToggleDatasetLikeByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountResponse.FromString,
                )
        self.GetDatasetLikedByMyAccount = channel.unary_unary(
                '/api.AccountAPI/GetDatasetLikedByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountResponse.FromString,
                )
        self.ToggleModelLikeByMyAccount = channel.unary_unary(
                '/api.AccountAPI/ToggleModelLikeByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountResponse.FromString,
                )
        self.GetModelLikedByMyAccount = channel.unary_unary(
                '/api.AccountAPI/GetModelLikedByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountResponse.FromString,
                )
        self.ToggleProjectLikeByMyAccount = channel.unary_unary(
                '/api.AccountAPI/ToggleProjectLikeByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountResponse.FromString,
                )
        self.GetProjectLikedByMyAccount = channel.unary_unary(
                '/api.AccountAPI/GetProjectLikedByMyAccount',
                request_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountResponse.FromString,
                )


class AccountAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAccountViewByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountViewById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyAccountView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrganizationAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleDatasetLikeByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetLikedByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleModelLikeByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelLikedByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleProjectLikeByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectLikedByMyAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccountViewByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountViewByName,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameResponse.SerializeToString,
            ),
            'GetAccountViewById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountViewById,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdResponse.SerializeToString,
            ),
            'GetMyAccountView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyAccountView,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateAccountResponse.SerializeToString,
            ),
            'CreateOrganizationAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganizationAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountResponse.SerializeToString,
            ),
            'CreateApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApiKey,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyResponse.SerializeToString,
            ),
            'ToggleDatasetLikeByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleDatasetLikeByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountResponse.SerializeToString,
            ),
            'GetDatasetLikedByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetLikedByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountResponse.SerializeToString,
            ),
            'ToggleModelLikeByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleModelLikeByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountResponse.SerializeToString,
            ),
            'GetModelLikedByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelLikedByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountResponse.SerializeToString,
            ),
            'ToggleProjectLikeByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleProjectLikeByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountResponse.SerializeToString,
            ),
            'GetProjectLikedByMyAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectLikedByMyAccount,
                    request_deserializer=api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountRequest.FromString,
                    response_serializer=api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.AccountAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAccountViewByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetAccountViewByName',
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountViewById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetAccountViewById',
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetAccountViewByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMyAccountView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetMyAccountView',
            api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetMyAccountViewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/CreateAccount',
            api_dot_service_dot_account_dot_account__api__pb2.CreateAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.CreateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateOrganizationAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/CreateOrganizationAccount',
            api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.CreateOrganizationAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/CreateApiKey',
            api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.CreateApiKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToggleDatasetLikeByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/ToggleDatasetLikeByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.ToggleDatasetLikeByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDatasetLikedByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetDatasetLikedByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetDatasetLikedByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToggleModelLikeByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/ToggleModelLikeByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.ToggleModelLikeByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelLikedByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetModelLikedByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetModelLikedByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ToggleProjectLikeByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/ToggleProjectLikeByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.ToggleProjectLikeByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProjectLikedByMyAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.AccountAPI/GetProjectLikedByMyAccount',
            api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountRequest.SerializeToString,
            api_dot_service_dot_account_dot_account__api__pb2.GetProjectLikedByMyAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
