[project]
name = "sheepcord"
description = "Discord interactions library"
version = "0.1.0"
authors = [
    { name = "Shinobou", email = "86394469+Shinobou@users.noreply.github.com" }
]
dependencies = [
    "pydantic~=1.9.1",
    "blacksheep~=1.2.7",
    "aiohttp~=3.8.1"
]

[project.optional-dependencies]
dev = [
    "black",
    "mypy"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]