# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\py-client\.\couchbase_version.py
# at
#    2022-06-29 12:18:14.751732
__version__ = '4.0.2'