[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nester_monstrosity878"
version = "1.3.0"
authors = [
  { name="ObscureIT", email="akif.khan1704@gmail.com" },
]
description = "Used for printing nested python lists either by indentation or without"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"