#### black ####################################################################
[tool.black]
line-length = 80
skip-magic-trailing-comma = true
target-version = ["py39"]

#### coverage #################################################################
[tool.coverage]

[tool.coverage.run]
branch = true
data_file = ".coverage/data"
parallel = true
plugins = ["coverage_conditional_plugin"]

[tool.coverage.report]
fail_under = 100.0
skip_covered = true
skip_empty = true

[tool.coverage.html]
directory = ".coverage/html"

[tool.coverage.coverage_conditional_plugin.rules]
ge39 = "sys_version_info >= (3, 9)"
ge310 = "sys_version_info >= (3, 10)"
lt39 = "sys_version_info < (3, 9)"
lt310 = "sys_version_info < (3, 10)"

#### isort ####################################################################
[tool.isort]
atomic = true
case_sensitive = true
float_to_top = true
force_single_line = true
line_length = 80
lines_after_imports = 2
profile = "black"
remove_redundant_aliases = true
skip_gitignore = true

#### poetry ###################################################################
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dycw-utilities"
version = "0.2.1"
description = "Miscellaneous Python utilities"
authors = ["Derek Wan <d.wan@icloud.com>"]
packages = [ {include = "utilities", from = "src" } ]

[tool.poetry.dependencies]
python = "^3.9, <3.11"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
bump2version = "^1.0.1"
click = "^8.1.3"
coverage = { version = "^6.4.0", extras = ["toml"] }
coverage-conditional-plugin = "^0.5.0"
fastapi = "^0.78.0"
flake8 = "^4.0.1"
flake8-absolute-import = "^1.0.0.1"
flake8-annotations = "^2.9.0"
flake8-bandit = "^3.0.0"
flake8-bugbear = "^22.7.1"
flake8-comprehensions = "^3.10.0"
flake8-debugger = "^4.1.2"
flake8-eradicate = "^1.2.1"
flake8-no-pep420 = "^2.3.0"
flake8-pie = "^0.15.0"
flake8-print = "^5.0.0"
flake8-simplify = "^0.19.2"
flake8-unused-arguments = "^0.0.10"
hypothesis = "^6.48.3"
isort = "^5.10.1"
loguru = "^0.6.0"
memory-profiler = "^0.60.0"
nox = "^2022.1.7"
numpy = "^1.22.4"
pandas = "^1.4.3"
pandas-stubs = "^1.4.3"
poetry-deps-scanner = "^1.0.1"
pqdm = "^0.2.0"
pre-commit = "^2.18.1"
pyclean = "^2.2.0"
pyinstrument = "^4.2.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-instafail = "^0.4.2"
pytest-xdist = "^2.5.0"
sqlalchemy = "^1.4.36"
sqlalchemy2-stubs = "^0.0.2-alpha.22"
tempenv = "^2.0.0"
tqdm = "^4.64.0"
typed-settings = "^1.0.1"
typeguard = "^2.13.3"

#### pyright ##################################################################
[tool.pyright]
include = ["src"]
pythonVersion = "3.9"
executionEnvironments = [{ root = "src" }]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportMissingTypeArgument = false
reportPrivateUsage = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUntypedBaseClass = false
reportImplicitStringConcatenation = "error"
reportMissingSuperCall = "error"
reportPropertyTypeMismatch = "error"
reportUnnecessaryTypeIgnoreComment = "error"
reportUnusedCallResult = "error"

#### pytest ###################################################################
[tool.pytest.ini_options]
addopts = [
  "-rsxX",
  "--color=auto",
  "--cov=utilities",
  "--cov-config=pyproject.toml",
  "--cov-report=html",
  "--strict-markers",
  "--typeguard-packages=utilities",
]
filterwarnings = [
  "error",
  "ignore::DeprecationWarning",
  "ignore:Implicitly cleaning up <TemporaryDirectory '.*'>:ResourceWarning",
]
looponfailroots = ["src"]
minversion = "7.0"
testpaths = ["src/tests"]
xfail_strict = true
