[project]
name = "omoidasu"
version = "0.0.2"
authors = [
  { name="0djentd" },
]
description = "CLI for Omoidasu"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/0djentd/omoidasu"
"Bug Tracker" = "https://github.com/0djentd/omoidasu/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
omoidasu = "omoidasu.cli:main"
