[tool.poetry]
name = "pytcm"
version = "0.5.4"
description = "pytcm - Python Terminal Commands Manager"
authors = ["Alexis Beaulieu <alexisbeaulieu97@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/alexisbeaulieu97/pytcm"
repository = "https://github.com/alexisbeaulieu97/pytcm"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
python-semantic-release = "^7.29.1"
flake8 = "^4.0.1"
black = "^22.3.0"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.1"

[tool.poetry.urls]
"Changelog" = "https://github.com/alexisbeaulieu97/pytcm/blob/main/CHANGELOG.md"

[tool.semantic_release]
version_variable = [
    "pytcm/__init__.py:__version__",
]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]
version_pattern = [
    "VERSION:{version}"
]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"