[tool.poetry]
name = "colambo"
version = "0.1.0"
description = ""
authors = ["David Jimenez <djjimenez1@utpl.edu.ec>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
