[tool.poetry]
name = "joconst"
version = "0.1.13"
description = ""
authors = ["FangyangJz <fangyang.jing@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.1"
jotdx = "^0.1.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
