[build-system]
requires = [
    "asn1crypto == 1.4.0",
    "protobuf == 3.13.0",
    "pycryptodome == 3.9.8",
]
build-backend = "setuptools.build_meta"
[tool.poetry]
packages = [
    { include = "alfipy" },
]