[tool.poetry]
name = "s3-cli"
version = "0.1.0"
description = ""
authors = ["Diogo Neto <diogo.neto@promptlyhealth.com>"]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.24.18"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
