name: Docs
on:
  push:
    branches:
      - main
jobs:
  generate_docs:
    if: startsWith(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Generate Docs
        run: |
          touch docs/html/.gitkeep
          rm -rf docs/html
          git rm -r docs/html
          sphinx-build -M html docs_src/source docs/
      - name: Commit files
        run: |
          git config --local user.email "rhino_sdk@noreply.github.com"
          git config --local user.name "github-actions[bot]"
          touch docs/html/.gitkeep
          git add -f docs/html
          git commit -m "Autogenerate Documentation"
          git push
