[tool.poetry]
name = "gtfs_kit"
version = "5.2.3"
description = "A Python 3.8+ library for analyzing GTFS feeds."
authors = ["Alex Raichev <araichev@mrcagney.com>"]
readme = "README.rst"
license = "MIT"
repository = "https://github.com/mrcagney/gtfs_kit"
documentation = "https://mrcagney.github.io/gtfs_kit_docs"
exclude = ["tests", "docs"]

[tool.poetry.dependencies]
python = ">=3.8, <4"
pandas = ">=1"
shapely = ">=1"
pycountry = ">=19"
utm = ">=0"
json2html = ">=1"
geopandas = ">=0"
rtree = ">=0"
folium = ">=0"
requests = ">=2"

[tool.poetry.dev-dependencies]
jupyter = "*"
pytest = ">=6"
sphinx = ">=3"
pre-commit = ">=0"
black = ">22"
publish_sphinx_docs = ">=1.0"
matplotlib = ">=1"
pytest-socket = ">=0"
nbstripout = ">=0.5"

[build-system]
requires = ["poetry>=1"]
build-backend = "poetry.masonry.api"

