[build-system]
requires = [
    "setuptools >= 46.4.0",
    "setuptools_scm >= 6.2.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "lymph/_version.py"
local_scheme = "no-local-version"

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pycln]
all = true
