[tool.poetry]
name = "openfisca-france-reforms"
version = "1.0.116"
description = "Some reforms for French OpenFisca tax-benefit system"
authors = ["Emmanuel Raviart <emmanuel@raviart.com>"]
keywords = ["benefit", "france", "microsimulation", "reform", "social", "tax"]
license = "http://www.fsf.org/licensing/licenses/agpl-3.0.html"
repository = "https://git.leximpact.dev/leximpact/openfisca-france-reforms"

[tool.poetry.dependencies]
python = ">= 3.7"
openfisca-france = ">= 116.13.2"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
flake8-black = "^0.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openfisca.reforms"]
# landais_piketty_saez = "openfisca_france_reforms.landais_piketty_saez:LandaisPikettySaez"
# lfi_progressivite_bareme_impot_revenu = "openfisca_france_reforms.lfi_progressivite_bareme_impot_revenu:LfiProgressiviteBaremeImpotRevenu"
# plf_2022 = "openfisca_france_reforms.plf_2022:Plf2022"
reforme_test_1 = "openfisca_france_reforms.reforme_test_1:ReformeTest1"
