# @package _global_

# run in experiment mode with:
# `python run.py mode=exp name=experiment_name`

experiment_mode: True

hydra:
  # sets output paths for all file logs to `logs/experiment/name'
  run:
    dir: logs/experiments/${datamodule.dataset}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/experiments/${datamodule.dataset}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
