[tool.poetry]
name = "tesseract-olap"
version = "0.1.0"
description = "A simple OLAP library."
authors = ["Francisco Abarzua <francisco@datawheel.us>"]
license = "MIT"
readme = "PACKAGE.md"

[tool.poetry.dependencies]
python = "^3.7.9"
asynch = {version = "^0.1.0", optional = true}
cached-property = "^1.5.2"
httpx = "^0.18.2"
immutables = "^0.16"
logiclayer = {version = "^0.1.0", optional = true}
lxml = "^4.6.3"
orjson = "^3.6.2"
PyPika = "^0.48.8"
typing-extensions = "^4.2.0"
sqlparse = "^0.4.2"

[tool.poetry.dev-dependencies]
asynch = "^0.1.0"
fastapi = ">=0.70.0"
logiclayer = {path = "../logiclayer", develop = true}
pycycle = "^0.0.8"
pydocstyle = "^6.1.1"
pylint = "^2.12.2"
pytest = "^6.2.0"
pytest-asyncio = "^0.15.1"
requests = "^2.27.1"

[tool.poetry.extras]
clickhouse = ["asynch"]
logiclayer = ["logiclayer"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
