[tool.poetry]
name = "mlbee"
version = "0.1.0-alpha.3"
description = "mlbee cli: a multilingual aligner based on a machine learning model"
authors = ["ffreemt"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ffreemt/mlbee-cli"

[tool.poetry.dependencies]
python = "^3.8.3"
logzero = "^1.7.0"
set-loglevel = "^0.1.2"
icecream = "^2.1.1"
install = "^1.3.5"
about-time = "3.1.1"
pendulum = "^2.1.2"
typer = "^0.4.1"
cchardet = "^2.1.7"
pandas = "^1.4.2"
httpx = "^0.23.0"
Jinja2 = "^3.1.2"
XlsxWriter = "^3.0.3"
alive-progress = "^2.4.1"
sep-text = { version = "^0.1.0", optional = true }
tenacity = "^8.0.1"
fetch-radio-embed = "^0.1.0-alpha.0"
sklearn = "^0.0"
seg-text = "^0.1.2"
cmat2aset = "^0.1.0-alpha.7"
aset2pairs = "^0.1.0"
more-itertools = "^8.13.0"
fetch-radio-cmat2aset = "^0.1.0-alpha.0"

[tool.poetry.extras]
sep-text = ["sep-text"]

[tool.poe.executor]
type = "poetry"

[tool.poe.tasks]
memo = "echo poe test or poetry run poe test"
test = "pytest tests"
pyright = "pyright mlbee"
flake8 = "flake8 mlbee --ignore F401,E501,F841,C901"
check = ["pyright", "flake8"]
export = "poetry export --without-hashes -f requirements.txt -o requirements.txt"
build = "poetry build"
publish = "poetry publish"
release = ["test", "build", "publish"]
lint = { cmd = "pylint mlbee" }
isort = "isort tests mlbee"
black = "black tests mlbee"
format = ["isort", "black"]
docstyle = "pydocstyle --convention=google tests mlbee"
prerelease = {cmd = "poetry version prerelease && sync-version"}
tunnel = {cmd = "ssh -CN ip_or_hostname_defined_in_hosts -L 9091:127.0.0.1:9091"}

[tool.poetry.dev-dependencies]
pytest = "^7.1"
flake8 = "^3.9.2"
pydocstyle = "^6.1.1"
toml = "^0.10.2"
# tbump = "^6.3.2"
poethepoet = "^0.10.0"

[tool.poetry.scripts]
"mlbee" = "mlbee.__main__:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --doctest-modules"
log_cli = true
testpaths = [
    "tests",
    # "integration",
]

[tool.black]
skip-string-normalization = 0

[tool.isort]
profile = "black"
multi_line_output = 3
