[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vocore_screen"
version = "0.1.0"
authors = [
  { name="Nicolas Meisberger", email="vocore-screen@bitshift.wtf" },
]
description = "Library to control the Vocore Touchscreen"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Topic :: System :: Hardware :: Universal Serial Bus (USB) :: Human Interface Device (HID)",
    "Operating System :: OS Independent",
]
dependencies = [
  "pyusb"
]

[project.urls]
"Homepage" = "https://github.com/Orangensaft/vocore-screen-py"
"Bug Tracker" = "https://github.com/Orangensaft/vocore-screen-py/issues"