[tool.poetry]
name = "enderturing"
version = "0.8.0"
description = "Python SDK for EnderTuring speech toolkit"
authors = ["EnderTuring <info@enderturing.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://enderturing.com/"
repository = "https://github.com/EnderTuringHQ/enderturing-sdk-python"
keywords = ["ASR", "speech", "enderturing"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Telecommunications Industry",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
    "Topic :: Multimedia :: Sound/Audio :: Sound Synthesis",
]

[tool.poetry.dependencies]
python = "^3.8"
websockets = "^10.3"
requests = "^2.28.0"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pre-commit = "^2.19.0"
pytest-asyncio = "^0.18.3"

[tool.isort]
skip_gitignore = true
profile = "black"
force_single_line = false
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true
src_paths = ["enderturing", "tests"]
filter_files = true
known_first_party = "enderturing"

[tool.black]
line-length = 100
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
)/
'''

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = true
ignore-private = true
ignore-property-decorators = false
ignore-module = true
fail-under = 65
exclude = ["tests", "docs", "dist"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
verbose = 2
quiet = false
whitelist-regex = []
color = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
