
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-29T07:34:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d25a07c5591543cf1e914f557b94666f1bd8e8a",
 "version": "v1.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
