
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-29T15:35:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "281ffc0db46da1c0343da8ba23c8447bd17d19fd",
 "version": "0.2.10.post0.dev44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
