[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "blis==0.4.1",
    "catalogue==1.0.0",
    "certifi==2019.11.28",
    "click==7.1.2",
    "colorama==0.4.4",
    "cycler==0.10.0",
    "cymem==2.0.3",
    "fastai==1.0.60",
    "fastprogress==0.2.2",
    "idna==2.9",
    "Janome==0.4.1",
    "jieba==0.42.1",
    "Jinja2==2.11.1",
    "joblib==0.14.0",
    "kiwisolver==1.1.0",
    "MarkupSafe==1.1.1",
    "matplotlib==3.2.0",
    "murmurhash==1.0.2",
    "nltk==3.4.5",
    "numpy==1.19.5",
    "packaging==20.9",
    "pandas==1.1.5",
    "Pillow==8.4.0",
    "preshed==3.0.2",
    "pydantic==1.8.2",
    "pykotokenizer==0.0.3",
    "pyparsing==2.4.6",
    "pythainlp==2.1.4",
    "python-crfsuite==0.9.8",
    "python-dateutil==2.8.0",
    "pytz==2019.2",
    "pyvi==0.1.1",
    "PyYAML==5.3",
    "regex==2021.4.4",
    "requests==2.23.0",
    "scikit-learn==0.24.2",
    "scipy==1.4.1",
    "six==1.15.0",
    "sklearn-crfsuite==0.3.6",
    "spacy==2.2.4",
    "srsly==1.0.2",
    "tabulate==0.8.10",
    "thinc==7.4.0",
    "threadpoolctl==2.1.0",
    "tinydb==3.15.2",
    "torch==1.10.1",
    "torchvision==0.11.2",
    "tqdm==4.62.3",
    "typing-extensions==3.7.4.3",
    "urllib3==1.25.8",
    "wasabi==0.6.0",
    "somajo==2.2.1"
]
build-backend = "setuptools.build_meta"