description: Barème progressif de l'impôt sur le revenu
metadata:
  type: marginal_rate
  threshold_unit: currency
  rate_unit: /1
brackets:
- rate:
    2021-09-01:
      value: 0.01
  threshold:
    2021-09-01:
      value: 0
- rate:
    2021-09-01:
      value: 0.05
  threshold:
    2021-09-01:
      value: 10293
- rate:
    2021-09-01:
      value: 0.10
  threshold:
    2021-09-01:
      value: 15439
- rate:
    2021-09-01:
      value: 0.15
  threshold:
    2021-09-01:
      value: 20585
- rate:
    2021-09-01:
      value: 0.20
  threshold:
    2021-09-01:
      value: 27790
- rate:
    2021-09-01:
      value: 0.25
  threshold:
    2021-09-01:
      value: 30877
- rate:
    2021-09-01:
      value: 0.30
  threshold:
    2021-09-01:
      value: 33965
- rate:
    2021-09-01:
      value: 0.35
  threshold:
    2021-09-01:
      value: 38082
- rate:
    2021-09-01:
      value: 0.40
  threshold:
    2021-09-01:
      value: 44257
- rate:
    2021-09-01:
      value: 0.45
  threshold:
    2021-09-01:
      value: 61753
- rate:
    2021-09-01:
      value: 0.50
  threshold:
    2021-09-01:
      value: 102922
- rate:
    2021-09-01:
      value: 0.55
  threshold:
    2021-09-01:
      value: 144090
- rate:
    2021-09-01:
      value: 0.60
  threshold:
    2021-09-01:
      value: 267595
- rate:
    2021-09-01:
      value: 0.90
  threshold:
    2021-09-01:
      value: 411684
