[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'
[project]
name = 'pychatroom'
version = '0.2.6'
dependencies = ['prompt_toolkit==3.0.17']
[project.scripts]
chatroom = 'chatroom:main'
