# -*- encoding: utf-8 -*-
[tool.poetry]
name = "chonf"
version = "0.2.0"
description = "User config management made simple and powerful"
authors = ["João C. Rodrigues Jr. <jc.rodrigues1997@usp.br>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://gitlab.com/Ovenbird-j/chonf"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows :: Windows Vista",
    "Operating System :: Microsoft :: Windows :: Windows 7",
    "Operating System :: Microsoft :: Windows :: Windows 8",
    "Operating System :: Microsoft :: Windows :: Windows 8.1",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: MacOS"
]

    [tool.poetry.dependencies]
    python = "^3.9"
    toml = "^0.10.2"
    PyYAML = "^6.0"
    xmltodict = "^0.12.0"

    [tool.poetry.dev-dependencies]
    black = "^22.1.0"
    isort = "^5.10.1"
    pydocstyle = "^6.1.1"
    pytest = "^6.2.5"
    flake8 = "^4.0.1"
    blacken-docs = "^1.12.1"

    [tool.poetry.urls]
    "Bug Tracker" = "https://github.com/python-poetry/poetry/issues"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
