from .SubjectClassCreateView import SubjectClassCreateView
from .SubjectClassDeleteView import SubjectClassDeleteView
from .SubjectClassDetailView import SubjectClassDetailView
from .SubjectClassListView import SubjectClassListView
from .SubjectClassUpdateView import SubjectClassUpdateView
