POSITIVE = [
    'grinning face',
    'grinning face with big eyes',
    'grinning face with smiling eyes',
    'beaming face with smiling eyes',
    'grinning squinting face',
    'grinning face with sweat',
    'rolling on the floor laughing',
    'face with tears of joy',
    'slightly smiling face',
    'smiling face with smiling eyes',
    'smiling face with halo',
    'smiling face with hearts',
    'smiling face with heart-eyes',
    'star-struck',
    'face blowing a kiss',
    'kissing face',
    'smiling face',
    'smiling face',
    'kissing face with closed eyes',
    'kissing face with smiling eyes',
    'smiling face with tear',
    'face savoring food',
    'face with tongue',
    'winking face with tongue',
    'zany face',
    'squinting face with tongue',
    'money-mouth face',
    'smiling face with open hands',
    'saluting face',
    'cowboy hat face',
    'partying face',
    'smiling face with sunglasses',
    'nerd face',
    'face with monocle',
    'robot',
    'grinning cat',
    'grinning cat with smiling eyes',
    'cat with tears of joy',
    'smiling cat with heart-eyes',
    'smiling face with horns',
    'clown face',
    'alien',
    'kiss mark',
    'love letter',
    'kissing cat',
    'sparkling heart',
    'hundred points',
    'bomb',
    'sweat droplets',
    'waving hand',
    'raised hand',
    'vulcan salute',
    'OK hand',
    'victory hand',
    'crossed fingers',
    'love-you gesture',
    'sign of the horns',
    'call me hand',
    'oncoming fist',
    'clapping hands',
    'raising hands',
    'heart hands',
    'thumbs up',
    'handshake',
    'flexed biceps',
    'nail polish',
    'brain',
    'eye',
    'tongue',
    'mouth',
    'person gesturing OK',
    'man in tuxedo',
    'woman with veil',
    'pregnant woman',
    'person with crown',
    'ninja',
    'Santa Claus',
    'superhero',
    'kiss',
    'dog',
    'bank',
    'wine glass',
    'cocktail glass',
    'tropical drink',
    'beer mug',
    'clinking beer mugs',
    'clinking glasses',
    'star',
    'glowing star',
    'shooting star',
    'Christmas tree',
    'fireworks',
    'sparkler',
    'firecracker',
    'sparkles',
    'high voltage',
    'spouting whale',
    'whale',
    'dolphin',
    'magic wand',
    'bikini',
    'high-heeled shoe',
    'lipstick',
    'ATM sign',
    'cigarette',
    'fire',
    'party popper',
    'confetti ball',
    'balloon',
    'trophy',
    '1st place medal',
    '2nd place medal',
    '3rd place medal',
    'sports medal',
    'military medal',
    'wrapped gift',
    'ribbon',
    'slot machine',
    'joystick',
    'sunglasses',
    'top hat',
    'dollar banknote',
    'money bag',
    'rocket',
    'american football'
]


NEGATIVE = [
    'upside-down face',
    'zipper-mouth face',
    'face with raised eyebrow',
    'expressionless face',
    'face without mouth',
    'dotted line face',
    'face in clouds',
    'shushing face',
    'smirking face',
    'unamused face',
    'face with rolling eyes',
    'grimacing face',
    'face exhaling',
    'lying face',
    'relieved face',
    'pensive face',
    'sleepy face',
    'drooling face',
    'sleeping face',
    'face with medical mask',
    'face with thermometer',
    'face with head-bandage',
    'nauseated face',
    'face vomiting',
    'hot face',
    'cold face',
    'woozy face',
    'face with crossed-out eyes',
    'face with spiral eyes',
    'exploding head',
    'disguised face',
    'confused face',
    'face with diagonal mouth',
    'worried face',
    'slightly frowning face',
    'frowning face',
    'hushed face',
    'astonished face',
    'flushed face',
    'pleading face',
    'face holding back tears',
    'frowning face with open mouth',
    'anguished face',
    'fearful face',
    'anxious face with sweat',
    'sad but relieved face',
    'crying face',
    'loudly crying face',
    'face screaming in fear',
    'disappointed face',
    'downcast face with sweat',
    'weary face',
    'tired face',
    'face with steam from nose',
    'enraged face',
    'angry face',
    'face with symbols on mouth',
    'angry face with horns',
    'skull',
    'skull and crossbones',
    'pile of poo',
    'broken heart',
    'anger symbol',
    'collision',
    'middle finger',
    'thumbs down',
    'person pouting',
    'person facepalming',
    'person shrugging',
    'supervillain',
    'vampire',
    'zombie',
    'full moon',
    'cloud with lightning and rain',
    'lizard',
    'snake',
    'dragon face',
    'crocodile',
    'spider',
    'funeral urn',
    'coffin',
    'headstone',
    'fire extinguisher',
    'warning',
    'prohibited',
    'no entry',
    'tornado',
    'cross mark',
    'SOS button'

]
