[tool.pyright]
extraPaths = ["ecomment"]


[tool.black]
target-version = ["py39"]


[tool.isort]
profile="black"
py_version=39
line_length=120
skip_gitignore=true


[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.poetry]
name = "ecomment"
version = "0.1.3"
description = "Comments want to be free."
authors = ["Jeremiah England <englandtuning@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ecomment/ecomment"
documentation = "https://github.com/ecomment/ecomment/tree/master/README.md"
keywords = ["comment", "cli", "tool", "workflow"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "*"

[tool.poetry.scripts]
ecomment = "ecomment.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
