[project]
name = "pyCodeEncryptor"
version = "0.1.0"
authors = [
  { name="MAMOSKO", email="admin@mamoskomail.ml" },
]
description = "Python için kod şifreleyici//Code encryptor for Python.."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "http://mamosko.ml/pyEncryptor/doc.html"