[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "alber-package-calc"
version = "0.0.1"
authors = [
    { name="alberrc87", email="alberto.r.caballero.87@gmail.com" },
]
description = "Ejemplo de como crear un paquete"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/albertorc87/subir-paquete-pypi"
"Bug Tracker" = "https://github.com/albertorc87/subir-paquete-pypi/issues"