[tool.poetry]
name = "omni-cli"
version = "0.1.0"
description = ""
authors = ["Derrick <derrick@example.com>"]
readme = "README.md"

[tool.poetry.scripts]
omni-cli = "omni_cli.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.4.2"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
