# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.api.time_plan_api import TimePlanApi  # noqa: E501
from adapi_sdk.rest import ApiException


class TestTimePlanApi(unittest.TestCase):
    """TimePlanApi unit test stubs"""

    def setUp(self):
        self.api = adapi_sdk.api.time_plan_api.TimePlanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_time_plan_list(self):
        """Test case for add_time_plan_list

        create new time-plan  # noqa: E501
        """
        pass

    def test_create_time_plan(self):
        """Test case for create_time_plan

        create new time-plan  # noqa: E501
        """
        pass

    def test_delete_time_plan(self):
        """Test case for delete_time_plan

        delete specific time-plan  # noqa: E501
        """
        pass

    def test_edit_time_plan(self):
        """Test case for edit_time_plan

        modify specific time-plan  # noqa: E501
        """
        pass

    def test_get_time_plan(self):
        """Test case for get_time_plan

        get specific time-plan  # noqa: E501
        """
        pass

    def test_get_time_plan_list(self):
        """Test case for get_time_plan_list

        get all time-plan  # noqa: E501
        """
        pass

    def test_replace_time_plan(self):
        """Test case for replace_time_plan

        replace specific time-plan  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
