# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.api.static_route_api import StaticRouteApi  # noqa: E501
from adapi_sdk.rest import ApiException


class TestStaticRouteApi(unittest.TestCase):
    """StaticRouteApi unit test stubs"""

    def setUp(self):
        self.api = adapi_sdk.api.static_route_api.StaticRouteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_static_route_list(self):
        """Test case for add_static_route_list

        create new static-route  # noqa: E501
        """
        pass

    def test_create_static_route(self):
        """Test case for create_static_route

        create new static-route  # noqa: E501
        """
        pass

    def test_delete_static_route(self):
        """Test case for delete_static_route

        delete specific static-route  # noqa: E501
        """
        pass

    def test_edit_static_route(self):
        """Test case for edit_static_route

        modify specific static-route  # noqa: E501
        """
        pass

    def test_edit_static_route_list(self):
        """Test case for edit_static_route_list

        modify static-route  # noqa: E501
        """
        pass

    def test_get_static_route(self):
        """Test case for get_static_route

        get specific static-route  # noqa: E501
        """
        pass

    def test_get_static_route_0(self):
        """Test case for get_static_route_0

        get specific static-route  # noqa: E501
        """
        pass

    def test_get_static_route_list(self):
        """Test case for get_static_route_list

        get all static-route  # noqa: E501
        """
        pass

    def test_get_static_route_list_0(self):
        """Test case for get_static_route_list_0

        get all static-route  # noqa: E501
        """
        pass

    def test_replace_static_route(self):
        """Test case for replace_static_route

        replace specific static-route  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
