# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.api.alert_sms_api import AlertSmsApi  # noqa: E501
from adapi_sdk.rest import ApiException


class TestAlertSmsApi(unittest.TestCase):
    """AlertSmsApi unit test stubs"""

    def setUp(self):
        self.api = adapi_sdk.api.alert_sms_api.AlertSmsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_alert_sms_verify(self):
        """Test case for alert_sms_verify

        alert-sms verify  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
