# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.models.stat_active_standby_device_status_last_configure_synchronize import StatActiveStandbyDeviceStatusLastConfigureSynchronize  # noqa: E501
from adapi_sdk.rest import ApiException


class TestStatActiveStandbyDeviceStatusLastConfigureSynchronize(unittest.TestCase):
    """StatActiveStandbyDeviceStatusLastConfigureSynchronize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatActiveStandbyDeviceStatusLastConfigureSynchronize(self):
        """Test StatActiveStandbyDeviceStatusLastConfigureSynchronize"""
        # FIXME: construct object with mandatory attributes with example values
        # model = adapi_sdk.models.stat_active_standby_device_status_last_configure_synchronize.StatActiveStandbyDeviceStatusLastConfigureSynchronize()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
