# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.api.active_standby_join_api import ActiveStandbyJoinApi  # noqa: E501
from adapi_sdk.rest import ApiException


class TestActiveStandbyJoinApi(unittest.TestCase):
    """ActiveStandbyJoinApi unit test stubs"""

    def setUp(self):
        self.api = adapi_sdk.api.active_standby_join_api.ActiveStandbyJoinApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_active_standby_join(self):
        """Test case for create_active_standby_join

         active-standby-join  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
