# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.api.ospfv3_api import Ospfv3Api  # noqa: E501
from adapi_sdk.rest import ApiException


class TestOspfv3Api(unittest.TestCase):
    """Ospfv3Api unit test stubs"""

    def setUp(self):
        self.api = adapi_sdk.api.ospfv3_api.Ospfv3Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_edit_ospfv3(self):
        """Test case for edit_ospfv3

        modify ospfv3  # noqa: E501
        """
        pass

    def test_get_ospfv3(self):
        """Test case for get_ospfv3

        get ospfv3  # noqa: E501
        """
        pass

    def test_replace_ospfv3(self):
        """Test case for replace_ospfv3

        replace ospfv3  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
