# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.models.config_scenario_slb_homepage_option import ConfigScenarioSlbHomepageOption  # noqa: E501
from adapi_sdk.rest import ApiException


class TestConfigScenarioSlbHomepageOption(unittest.TestCase):
    """ConfigScenarioSlbHomepageOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigScenarioSlbHomepageOption(self):
        """Test ConfigScenarioSlbHomepageOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = adapi_sdk.models.config_scenario_slb_homepage_option.ConfigScenarioSlbHomepageOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
