# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.api.proxy_api import ProxyApi  # noqa: E501
from adapi_sdk.rest import ApiException


class TestProxyApi(unittest.TestCase):
    """ProxyApi unit test stubs"""

    def setUp(self):
        self.api = adapi_sdk.api.proxy_api.ProxyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_edit_proxy(self):
        """Test case for edit_proxy

        modify proxy  # noqa: E501
        """
        pass

    def test_get_proxy(self):
        """Test case for get_proxy

        get proxy  # noqa: E501
        """
        pass

    def test_replace_proxy(self):
        """Test case for replace_proxy

        replace proxy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
