# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.api.dns_pre_rule_api import DnsPreRuleApi  # noqa: E501
from adapi_sdk.rest import ApiException


class TestDnsPreRuleApi(unittest.TestCase):
    """DnsPreRuleApi unit test stubs"""

    def setUp(self):
        self.api = adapi_sdk.api.dns_pre_rule_api.DnsPreRuleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_dns_pre_rule_list(self):
        """Test case for add_dns_pre_rule_list

        create new dns-pre-rule  # noqa: E501
        """
        pass

    def test_create_dns_pre_rule(self):
        """Test case for create_dns_pre_rule

        create new dns-pre-rule  # noqa: E501
        """
        pass

    def test_delete_dns_pre_rule(self):
        """Test case for delete_dns_pre_rule

        delete specific dns-pre-rule  # noqa: E501
        """
        pass

    def test_edit_dns_pre_rule(self):
        """Test case for edit_dns_pre_rule

        modify specific dns-pre-rule  # noqa: E501
        """
        pass

    def test_get_dns_pre_rule(self):
        """Test case for get_dns_pre_rule

        get specific dns-pre-rule  # noqa: E501
        """
        pass

    def test_get_dns_pre_rule_list(self):
        """Test case for get_dns_pre_rule_list

        get all dns-pre-rule  # noqa: E501
        """
        pass

    def test_replace_dns_pre_rule(self):
        """Test case for replace_dns_pre_rule

        replace specific dns-pre-rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
