# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.api.interface_api import InterfaceApi  # noqa: E501
from adapi_sdk.rest import ApiException


class TestInterfaceApi(unittest.TestCase):
    """InterfaceApi unit test stubs"""

    def setUp(self):
        self.api = adapi_sdk.api.interface_api.InterfaceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_statistics_of_interface_list(self):
        """Test case for get_statistics_of_interface_list

        get all interface statistics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
