# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.models.stat_ospf_neighbors_detail_list import StatOspfNeighborsDetailList  # noqa: E501
from adapi_sdk.rest import ApiException


class TestStatOspfNeighborsDetailList(unittest.TestCase):
    """StatOspfNeighborsDetailList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatOspfNeighborsDetailList(self):
        """Test StatOspfNeighborsDetailList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = adapi_sdk.models.stat_ospf_neighbors_detail_list.StatOspfNeighborsDetailList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
