# coding: utf-8

"""
    Sangfor AD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 7.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import adapi_sdk
from adapi_sdk.api.token_api import TokenApi  # noqa: E501
from adapi_sdk.rest import ApiException


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self):
        self.api = adapi_sdk.api.token_api.TokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_token_list(self):
        """Test case for add_token_list

        create new token  # noqa: E501
        """
        pass

    def test_create_token(self):
        """Test case for create_token

        create new token  # noqa: E501
        """
        pass

    def test_delete_token(self):
        """Test case for delete_token

        delete specific token  # noqa: E501
        """
        pass

    def test_get_token(self):
        """Test case for get_token

        get specific token  # noqa: E501
        """
        pass

    def test_get_token_list(self):
        """Test case for get_token_list

        get all token  # noqa: E501
        """
        pass

    def test_refresh_token(self):
        """Test case for refresh_token

        refresh new token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
