name: Project Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
      - name: Test with unittest
        run: python3 -m unittest -v ./typeddict_validator/validate_test.py
