[tool.poetry]
authors = [" "]
description = ""
name = "enil"
version = "0.2.2"

[tool.poetry.dependencies]
PyQRCode = "^1.2.1"
httplib2 = "^0.20.4"
httpx = "^0.23.0"
hyper = "^0.7.0"
"lesting.api.client" = "^0.1.1"
pycryptodome = "^3.15.0"
python = ">=3.7,<4"
python-axolotl-curve25519 = "^0.4.1"
requests = "^2.28.0"
rsa = "^4.8"
thrift = "^0.16.0"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
pytest = "^7.1.2"
