[tool.poetry]
name = "pytest-chunks"
version = "0.2.0"
description = "Run only a chunk of your test suite"
authors = ["Mehdi Abaakouk <sileht@sileht.net>"]
license = "Apache-2.0"
classifiers = ["Intended Audience :: Information Technology", "License :: OSI Approved :: Apache Software License", "Operating System :: POSIX", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.10"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pytest = ">=6.0.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^22.6.0"
isort = "^5.10.1"
mypy = "^0.961"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"

[tool.poetry.plugins]

[tool.poetry.plugins.pytest11]
  pytest_chunks = "pytest_chunks"

[tool.black]
target-version = ['py310']

[tool.mypy]
ignore_missing_imports = true
disallow_incomplete_defs = true
warn_unused_ignores = true
warn_unused_configs = true
disallow_any_generics = true
warn_return_any = true
files = ["pytest_chunks"]
disallow_subclassing_any = true
warn_redundant_casts = true
strict_equality = true
no_implicit_optional = true
disallow_untyped_decorators = true
show_error_codes = true
disallow_untyped_calls = true

[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = "2"
force_sort_within_sections = true
known_first_party = "pytest_chunks"
default_section = "THIRDPARTY"
