[tool.poetry]
name = "sensor_position_dataset_helper"
version = "1.2.0"
description = "A helper for the SensorPositionDateset (recorded 2019, published 2021)"
license = "MIT"
authors = ["Arne Küderle <arne.kuederle@fau.de>"]
readme = "README.md"
repository = "https://github.com/mad-lab-fau/sensor_position_dataset_helper"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
numpy = "^1.20.0"
scipy = "^1"
c3d = "^0.3.0"
typing-extensions = ">=3.7.4"
nilspodlib = "^3.1"
imucal = "^2.0.0"
joblib = "^1.0.0"
GitPython = "^3.1.13"
pandas = "^1.2.2"
tpcp = ">=0.3.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | docs
    | build
    | dist
    | \.virtual_documents
  )/
)
'''
