root = "."
tmp_dir = ".air"

[build]
cmd = "make backend"
bin = "{{APP_NAME}}"
include_ext = ["go", "tmpl"]
exclude_dir = ["storage", ".github", "docs"]
include_dir = ["internal", "pkg"]
exclude_regex = ["_test.go$"]
