[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Tangiball"
version = "0.4.2"
authors = [
{name="Joseph Starkey",email="jds40@sussex.ac.uk"},
]
description = "Small package to identify and analyse peaks in a specific time-series"
readme = "README.md"
requires-python = ">=3.9"

classifiers = [
"Programming Language :: Python :: 3",
"License :: OSI Approved :: MIT License",
"Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/D-I-S-C-U-S/Tangiball"
