# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: problem.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproblem.proto\"H\n\x18ProblemPerformanceMetric\x12\x0e\n\x06metric\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\x12\x11\n\tpos_label\x18\x03 \x01(\t\"X\n\x07Problem\x12\x15\n\rtask_keywords\x18\x08 \x03(\t\x12\x36\n\x13performance_metrics\x18\x07 \x03(\x0b\x32\x19.ProblemPerformanceMetric\"~\n\rProblemTarget\x12\x14\n\x0ctarget_index\x18\x01 \x01(\x05\x12\x13\n\x0bresource_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63olumn_index\x18\x03 \x01(\x05\x12\x13\n\x0b\x63olumn_name\x18\x04 \x01(\t\x12\x17\n\x0f\x63lusters_number\x18\x05 \x01(\x05\"v\n\x15ProblemPrivilegedData\x12\x1d\n\x15privileged_data_index\x18\x01 \x01(\x05\x12\x13\n\x0bresource_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63olumn_index\x18\x03 \x01(\x05\x12\x13\n\x0b\x63olumn_name\x18\x04 \x01(\t\"k\n\x12\x46orecastingHorizon\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63olumn_index\x18\x02 \x01(\x05\x12\x13\n\x0b\x63olumn_name\x18\x03 \x01(\t\x12\x15\n\rhorizon_value\x18\x04 \x01(\x01\"\xa6\x01\n\x0cProblemInput\x12\x12\n\ndataset_id\x18\x01 \x01(\t\x12\x1f\n\x07targets\x18\x02 \x03(\x0b\x32\x0e.ProblemTarget\x12/\n\x0fprivileged_data\x18\x03 \x03(\x0b\x32\x16.ProblemPrivilegedData\x12\x30\n\x13\x66orecasting_horizon\x18\x04 \x01(\x0b\x32\x13.ForecastingHorizon\"4\n\x10\x44\x61taAugmentation\x12\x0e\n\x06\x64omain\x18\x01 \x03(\t\x12\x10\n\x08keywords\x18\x02 \x03(\t\"\xe1\x01\n\x12ProblemDescription\x12\x19\n\x07problem\x18\x01 \x01(\x0b\x32\x08.Problem\x12\x1d\n\x06inputs\x18\x02 \x03(\x0b\x32\r.ProblemInput\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x0e\n\x06\x64igest\x18\x07 \x01(\t\x12,\n\x11\x64\x61ta_augmentation\x18\x08 \x03(\x0b\x32\x11.DataAugmentation\x12\x13\n\x0bother_names\x18\t \x03(\tB+Z)gitlab.com/datadrivendiscovery/automl-rpcb\x06proto3')



_PROBLEMPERFORMANCEMETRIC = DESCRIPTOR.message_types_by_name['ProblemPerformanceMetric']
_PROBLEM = DESCRIPTOR.message_types_by_name['Problem']
_PROBLEMTARGET = DESCRIPTOR.message_types_by_name['ProblemTarget']
_PROBLEMPRIVILEGEDDATA = DESCRIPTOR.message_types_by_name['ProblemPrivilegedData']
_FORECASTINGHORIZON = DESCRIPTOR.message_types_by_name['ForecastingHorizon']
_PROBLEMINPUT = DESCRIPTOR.message_types_by_name['ProblemInput']
_DATAAUGMENTATION = DESCRIPTOR.message_types_by_name['DataAugmentation']
_PROBLEMDESCRIPTION = DESCRIPTOR.message_types_by_name['ProblemDescription']
ProblemPerformanceMetric = _reflection.GeneratedProtocolMessageType('ProblemPerformanceMetric', (_message.Message,), {
  'DESCRIPTOR' : _PROBLEMPERFORMANCEMETRIC,
  '__module__' : 'problem_pb2'
  # @@protoc_insertion_point(class_scope:ProblemPerformanceMetric)
  })
_sym_db.RegisterMessage(ProblemPerformanceMetric)

Problem = _reflection.GeneratedProtocolMessageType('Problem', (_message.Message,), {
  'DESCRIPTOR' : _PROBLEM,
  '__module__' : 'problem_pb2'
  # @@protoc_insertion_point(class_scope:Problem)
  })
_sym_db.RegisterMessage(Problem)

ProblemTarget = _reflection.GeneratedProtocolMessageType('ProblemTarget', (_message.Message,), {
  'DESCRIPTOR' : _PROBLEMTARGET,
  '__module__' : 'problem_pb2'
  # @@protoc_insertion_point(class_scope:ProblemTarget)
  })
_sym_db.RegisterMessage(ProblemTarget)

ProblemPrivilegedData = _reflection.GeneratedProtocolMessageType('ProblemPrivilegedData', (_message.Message,), {
  'DESCRIPTOR' : _PROBLEMPRIVILEGEDDATA,
  '__module__' : 'problem_pb2'
  # @@protoc_insertion_point(class_scope:ProblemPrivilegedData)
  })
_sym_db.RegisterMessage(ProblemPrivilegedData)

ForecastingHorizon = _reflection.GeneratedProtocolMessageType('ForecastingHorizon', (_message.Message,), {
  'DESCRIPTOR' : _FORECASTINGHORIZON,
  '__module__' : 'problem_pb2'
  # @@protoc_insertion_point(class_scope:ForecastingHorizon)
  })
_sym_db.RegisterMessage(ForecastingHorizon)

ProblemInput = _reflection.GeneratedProtocolMessageType('ProblemInput', (_message.Message,), {
  'DESCRIPTOR' : _PROBLEMINPUT,
  '__module__' : 'problem_pb2'
  # @@protoc_insertion_point(class_scope:ProblemInput)
  })
_sym_db.RegisterMessage(ProblemInput)

DataAugmentation = _reflection.GeneratedProtocolMessageType('DataAugmentation', (_message.Message,), {
  'DESCRIPTOR' : _DATAAUGMENTATION,
  '__module__' : 'problem_pb2'
  # @@protoc_insertion_point(class_scope:DataAugmentation)
  })
_sym_db.RegisterMessage(DataAugmentation)

ProblemDescription = _reflection.GeneratedProtocolMessageType('ProblemDescription', (_message.Message,), {
  'DESCRIPTOR' : _PROBLEMDESCRIPTION,
  '__module__' : 'problem_pb2'
  # @@protoc_insertion_point(class_scope:ProblemDescription)
  })
_sym_db.RegisterMessage(ProblemDescription)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)gitlab.com/datadrivendiscovery/automl-rpc'
  _PROBLEMPERFORMANCEMETRIC._serialized_start=17
  _PROBLEMPERFORMANCEMETRIC._serialized_end=89
  _PROBLEM._serialized_start=91
  _PROBLEM._serialized_end=179
  _PROBLEMTARGET._serialized_start=181
  _PROBLEMTARGET._serialized_end=307
  _PROBLEMPRIVILEGEDDATA._serialized_start=309
  _PROBLEMPRIVILEGEDDATA._serialized_end=427
  _FORECASTINGHORIZON._serialized_start=429
  _FORECASTINGHORIZON._serialized_end=536
  _PROBLEMINPUT._serialized_start=539
  _PROBLEMINPUT._serialized_end=705
  _DATAAUGMENTATION._serialized_start=707
  _DATAAUGMENTATION._serialized_end=759
  _PROBLEMDESCRIPTION._serialized_start=762
  _PROBLEMDESCRIPTION._serialized_end=987
# @@protoc_insertion_point(module_scope)
