[tool.poetry]
name = "bento-tools"
packages = [{ include = "bento" }]
include = ["bento/datasets/datasets.csv", "bento/models/**/*"]
version = "1.0.1"
description = "A toolkit for subcellular analysis of spatial transcriptomics data"
authors = ["Clarence Mah <ckmah@ucsd.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
anndata = "^0.7.6"
astropy = "^5.0"
cell2cell = "^0.5.10"
dask-geopandas = "^0.1.3"
geopandas = "^0.10.0"
matplotlib = "^3.2"
matplotlib-scalebar = "^0.8.1"
myst-parser = { version = "^0.18.0", optional = true }
nbsphinx = {version = "^0.8.9", optional = true }
pandas = "<=1.2.5"
pygeos = "^0.12.0"
scanpy = "^1.9.1"
scipy = "^1.7.0"
seaborn = "^0.11.0"
Shapely = "^1.8.2"
Sphinx = { version = "^4.1.2", optional = true }
sphinx-autobuild = { version = "^2021.3.14", optional = true }
sphinx-book-theme = { version = "^0.3.2", optional = true }
sphinx-gallery = { version = "^0.10.1", optional = true }
statsmodels = "^0.13.2"
torch = { version = "^1.9.0", optional = true }
tqdm = "^4.64.0"
UpSetPlot = "^0.6.1"
numba = "^0.55.2"
xgboost = "1.4.0"
emoji = "^1.7.0"

[tool.poetry.extras]
torch = ["torch"]
docs = ["Sphinx", "sphinx-autobuild", "sphinx-book-theme", "nbsphinx", "sphinx-gallery", "myst-parser"]

[tool.setuptools]
py_modules=[]

[build-system]
requires = ["poetry-core>=1.0.0", 'setuptools']
build-backend = "poetry.core.masonry.api"
