[project]
name = "jobbatch"
version = "1.0.2"
authors = [
  { name="Quentin Stafford-Fraser", email="quentin@pobox.com" },
]
description = "A utility for splitting tasks up into batches"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.5"
classifiers = [
    "Programming Language :: Python :: 3",
]

[console_scripts]
jobbatch = "jobbatch:main"

[project.urls]
"Homepage" = "https://github.com/quentinsf/jobbatch"
"Bug Tracker" = "https://github.com/quentinsf/jobbatch/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
