[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "python-datastream"
authors = [{name = "NekoNekoNyan", email = "pasha2001dpa@ya.ru"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3"
]
dynamic = ["version", "description"]
requires-python = ">=3.6"

[project.urls]
Home = "https://github.com/neko-neko-nyan/datastream"

[tool.flit.module]
name = "datastream"
