[tool.poetry]
name = "cz_flexiv"
version = "0.1.1"
description = ""
authors = ["yunpeng.zhan <yunpeng.zhan@flexiv.com>"]

[tool.poetry.dependencies]
python = "^3.7"
commitizen = "^2.27.1"
requests = "^2.28.1"


[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
