# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': '..'}

packages = \
['nonebot_plugin_myb_exchange',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages._distutils_hack',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.cli',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.commands',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.distributions',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.index',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.locations',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.metadata',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.models',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.network',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.operations',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.operations.build',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.operations.install',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.req',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.resolution',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.resolution.legacy',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.resolution.resolvelib',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.utils',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._internal.vcs',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.cachecontrol',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.certifi',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.chardet',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.chardet.cli',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.chardet.metadata',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.colorama',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.distlib',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.distlib._backport',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.html5lib',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.html5lib._trie',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.html5lib.filters',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.html5lib.treebuilders',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.idna',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.msgpack',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.packaging',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pep517',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pep517.in_process',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pkg_resources',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.platformdirs',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.progress',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pygments',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pygments.filters',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pygments.formatters',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pygments.lexers',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pygments.styles',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pyparsing',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.pyparsing.diagram',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.requests',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.resolvelib',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.resolvelib.compat',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.rich',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.tenacity',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.tomli',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.urllib3',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.urllib3.contrib',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.urllib3.packages',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.urllib3.util',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pip._vendor.webencodings',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pkg_resources',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pkg_resources._vendor',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pkg_resources._vendor.importlib_resources',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pkg_resources._vendor.jaraco',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pkg_resources._vendor.jaraco.text',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pkg_resources._vendor.more_itertools',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pkg_resources._vendor.packaging',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.pkg_resources.extern',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._distutils',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._distutils.command',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._vendor',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._vendor.importlib_metadata',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._vendor.importlib_resources',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._vendor.jaraco',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._vendor.jaraco.text',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._vendor.more_itertools',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._vendor.nspektr',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._vendor.packaging',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools._vendor.tomli',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools.command',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools.config',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools.config._validate_pyproject',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.setuptools.extern',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.wheel',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.wheel.cli',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.wheel.vendored',
 'nonebot_plugin_myb_exchange..venv.Lib.site-packages.wheel.vendored.packaging',
 'nonebot_plugin_myb_exchange..venv.Scripts']

package_data = \
{'': ['*'],
 'nonebot_plugin_myb_exchange': ['.venv/*',
                                 '.venv/Lib/site-packages/pip-22.0.4.dist-info/*',
                                 '.venv/Lib/site-packages/setuptools-62.1.0.dist-info/*',
                                 '.venv/Lib/site-packages/wheel-0.37.1.dist-info/*',
                                 'dist/*']}

install_requires = \
['httpx>=0.23.0,<0.24.0',
 'nonebot-adapter-onebot>=2.0.0-beta.1,<3.0.0',
 'nonebot-plugin-apscheduler>=0.1.2,<0.2.0',
 'nonebot2>=2.0.0-beta.4,<3.0.0']

setup_kwargs = {
    'name': 'nonebot-plugin-myb-exchange',
    'version': '1.0.0',
    'description': 'Nonebot2米游币商品自动兑换插件',
    'long_description': '# nonebot-plugin-myb-exchange\nNonebot2米游币商品自动兑换插件\n\n## 使用方法\n> 由于涉及到cookie、地址等敏感信息，所以仅限**私聊**Bot使用\n\n- 发送`myb`，跟随Bot的指引一步一步录入信息\n- 发送`myb_info`可查看已录入的兑换计划\n- 发送`myb_delete`可一键删除所有你的兑换计划\n',
    'author': '惜月',
    'author_email': '277073121@qq.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/CMHopeSunshine/LittlePaimon/tree/Bot/src/plugins/nonebot_plugin_myb_exchange',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.7.3,<4.0.0',
}


setup(**setup_kwargs)
