[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "DataBoy"
version = "1.0.0"
authors = [
  { name="Cosmic Dev", email="alinafea4real@gmail.com" },
]
description = "This is a python package for easily storing, reading and manipulating data."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/aliNafea/PyDataMan"
"Bug Tracker" = "https://github.com/aliNafea/PyDataMan/issues"