[tool.poetry]
name = "sword-to-json"
version = "2.1.1"
description = "Generate JSON Files of Bible Translations from SWORD Modules"
license = "GPL-3.0-or-later"

authors = ["Evans <evans@fundi.dev>"]

readme = "README.md"

homepage = "https://github.com/evnskc/sword-to-json"

repository = "https://github.com/evnskc/sword-to-json"

documentation = "https://github.com/evnskc/sword-to-json"

keywords = ["sword", "bible text", "json"]

packages = [
    { include = "sword_to_json" },
    { include = "utils" }
]

[tool.poetry.dependencies]
python = "^3.10"
pysword = "^0.2.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
jsonschema = "^4.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sword-to-json = "sword_to_json.__main__:main"