[build-system]
requires = ["setuptools>=61.0", "requests"]
build-backend = "setuptools.build_meta"

[project]
name = "scoreunlocked"
version = "0.0.1"
authors = [
    { name = "Tank King", email = "tankking9833@gmail.com" },
]
description = "A simple package for using the ScoreUnlocked leaderboard system running at scoreunlocked.pythonanywhere.com"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/tank-king/scoreunlocked"
"Bug Tracker" = "https://github.com/tank-king/scoreunlocked/issues"