[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
known_first_party = "wandb"
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.black]
line-length = 120

[tool.nbqa.addopts]
pylint = [
    "--disable=C0103,C0114,C0116,E0401,R0801,W0106"
]
