[tool.black]
line-length = 130
target_version = ["py310"]
include = '''
(
    ^/tests/.*[.]py$
  | ^/app/.*[.]py$
  | ^/mb_base1/.*[.]py$
  | ^/setup[.]py
)
'''
exclude = '''
(
     __pycache__
     | ^/.venv
     | ^/.mypy_cache
     | ^/*.egg-info
     | ^/build
     | ^/dist
)
'''

[tool.isort]
line_length = 130
use_parentheses = "True"
include_trailing_comma = "True"
multi_line_output = 3
default_section = "THIRDPARTY"
known_first_party = "app,mb_base1"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.mypy]
python_version = "3.10"
warn_no_return = false
