[tool.poetry]
name = "hmp-aviel"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.1.3"
requests = "^2.28.0"
flake8 = "^4.0.1"
black = "^22.3.0"
flake8-black = "^0.3.3"
flake8-import-order = "^0.18.1"
flake8-bugbear = "^22.6.22"
flake8-bandit = "^3.0.0"
pre-commit = "^2.19.0"
mypy = "^0.961"
desert = "^2020.11.18"
marshmallow = "^3.17.0"
typeguard = "^2.13.3"
Pygments = "^2.12.0"
Sphinx = "^4.0.0"
sphinx-autodoc-typehints = "^1.17"
types-requests = "^2.28.0"
codecov = "^2.1.12"
coverage = {extras = ["toml"], version = "^6.4.1"}
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
coverage = {extras = ["toml"], version = "^6.4.1"}
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.1"
autopep8 = "^1.6.0"
flake8-annotations = "^2.9.0"
flake8-docstrings = "^1.6.0"
darglint = "^1.8.1"
xdoctest = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

description = "The hypermodern Python project"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/<your-username>/hypermodern-python"
repository = "https://github.com/<your-username>/hypermodern-python"
keywords = ["hypermodern"]

[tool.poetry.scripts]
hmp-aviel = "hmp_aviel.console:main"


[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["hmp_aviel"]

[tool.coverage.report]
show_missing = true
fail_under = 100
