[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "linalg-backends"
version = "0.0.1-beta"
authors = [
  { name="Aaron Mishkin", email="amishkin@cs.stanford.edu" },
]
description = "Linear Algebra Backends: a lightweight interface for linear algebra engines."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "torch",
    "opt_einsum",
]

[tool.setuptools.package-data]
lab = ["py.typed"]

[project.urls]
"Homepage" = "https://github.com/aaronpmishkin/lab"
"Bug Tracker" = "https://github.com/aaronpmishkin/lab/issues"
