[tool.poetry]
name = "signed-pickle"
version = "1.0.1"
description = "Description"
authors = ["Daniel Sullivan <mumblepins@users.noreply.github.com>"]
license = "LGPL-3.0-or-later"
repository = "https://github.com/mumblepins/signed-pickle/"
documentation = "https://mumblepins.github.io/signed-pickle/"
readme = "README.md"
packages = [{ include = "signed_pickle", from = "src" }]

[tool.poetry.dependencies]
python = "^3.7"
lz4 = { version="*",optional=true}

[tool.poetry.dev-dependencies]
pylint = "^2.13.0"
pytest = "^7.1.1"

coverage = "^6.3.2"
pre-commit = "^2.15.0"
Sphinx = "^5.0"
sphinx-rtd-theme = "^1.0"
pytest-cov = "^3.0.0"
pylint-pytest = "^1.1.2"
pytest-xdist = "^2.5.0"
myst-parser = "*"

importlib-resources = { version = "^5.7.1", python = "<3.9" }
bump2version = "^1.0.1"

[tool.poetry.extras]
lz4=['lz4']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[[tool.mypy.overrides]]
module = [
    "lz4",
]
ignore_missing_imports = true
